### ISSUE TITLE
"Remember me" functionality

### ISSUE THREAD

**Issue by kevinansfield** [heartsentwined/ember-auth#1]
Hi,

Perhaps I'm missing something but does this package at the moment allow for "remember me" type functionality?

It seems as though it's currently set up for apps that require you to sign-in at the start of every session, is that correct?

**Comment by heartsentwined** [comment]
**EDIT**

Feature accepted, will implement it in coming release.

**Comment by heartsentwined** [comment]
@kevinansfield remember me feature implemented, closing issue.
