### ISSUE TITLE
Nested token key property

### ISSUE THREAD

**Issue by miguelcobain** [heartsentwined/ember-auth#100]
I would like to set my `tokenKey` property to a nested property (i.e inside an object and not in the root object). For example `tokenKey : 'user.token'`. Wrapped object responses are typical, specially when using ember that, so I think that this makes sense.

The same applies to `tokenIdKey`.

Is it possible to specify how ember-auth retrieves the token from the response?

Thank you.

**Comment by heartsentwined** [comment]
Take a look at #63

**Comment by miguelcobain** [comment]
Exactly what I was looking for.

Sorry, my bad. Should have looked better.
Thank you!

**Comment by heartsentwined** [comment]
Glad it helped.
