### ISSUE TITLE
authRedirectable redirects even when user is signed in.

### ISSUE THREAD

**Issue by ekampp** [heartsentwined/ember-auth#101]
Hi there. 

I have a problem, which is that after setting up the authRedirectable module (see below), after I sign in and reload, I will be redirected to the login route again. 

Here is my setup:

``` coffeescript
# auth.js.coffee
App.Auth = Ember.Auth.create
  modules: ['emberData', 'authRedirectable']
  authRedirectable:
    route: 'login'
App.Auth.on 'authAccess', ->
  debug.error "Not authenticated.."

# application_route.js.coffee
App.ApplicationRoute = Ember.Route.extend(App.Auth.AuthRedirectable)
App.ApplicationRoute = App.ApplicationRoute.extend
  beforeModel: ->
    if @signedIn
      debug.log "hello.."
    else
      debug.log "bang.."
    @_super.apply this, arguments

  signedIn: ->
    App.Auth.get('signedIn')

# dashboard_route.js.coffee
App.DashboardRoute = App.ApplicationRoute.extend
```

When navigating to `#/dashboards` (which is the protected route), I get redirected to `#/login` and see the following output in my console:

```
"hello.."
"Not Authenticated.."
```

So for me, that indicates that before setting the model in the application route the user is clearly signed in. So why is he redirected away from the route?

**Comment by heartsentwined** [comment]
I'll try to replicate this issue; meanwhile, I noticed that `signedIn` is not a computed property, is that intentional?

**Comment by ekampp** [comment]
@heartsentwined, "computed property"? Can you elaborate?

**Comment by heartsentwined** [comment]
I think you mean

``` coffeescript
App.ApplicationRoute = App.ApplicationRoute.extend
  # either
  signedIn: (-> App.Auth.get('signedIn') ).property('App.Auth.signedIn')
  # or
  signedIn: Em.computed.alias 'App.Auth.signedIn'
```

**Comment by ekampp** [comment]
Hmm.. The problem seems to apply even with that change.

**Comment by heartsentwined** [comment]
@ekampp at `9.x` (latest), `authRedirectable` got a slight rework, which, in addition with the general architectural change at `ember-auth`, should get rid of some subtle bugs from loading order and same ember run loops. Could you upgrade and see if the problem persists? The usual code-generating [docs](http://ember-auth.herokuapp.com/) and [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide) to help with the transition.

Please let me know if you cannot upgrade for whatever reason, I'd then dig into the `8.x` branch and try to reproduce the issue. Who knows, perhaps it would point to another unknown bug that went through to `9.x`. Or, of course, if the issue persists after upgrading.

**Comment by ekampp** [comment]
I will take a look later this week. Thanks.

**Comment by ekampp** [comment]
This seems to be fixed in 9.0

**Comment by ekampp** [comment]
Thanks a lot for you help! :+1:

**Comment by heartsentwined** [comment]
Glad it helped @ekampp
