### ISSUE TITLE
Ember Data 1.0.0-beta

### ISSUE THREAD

**Issue by seifsallam** [heartsentwined/ember-auth#102]
Any plans for supporting ember-data 1.0.0-beta?

**Comment by asia653** [comment]
+1

**Comment by KirillSuhodolov** [comment]
+1

**Comment by heartsentwined** [comment]
I'm not an `ember-data` user myself, so I'll need some input from devs who do use the lib. The following is the only break that I know of:
- `App.Foo.find(1)` becomes `store.find('foo', 1)`

anything else?

**Comment by seifsallam** [comment]
To be honest, I haven't tried migrating myself, as ember-auth didn't support it. So you might want to check these first.

https://github.com/emberjs/data/blob/master/TRANSITION.md
http://discuss.emberjs.com/t/migrating-from-ember-data-0-13-to-1-0-0-beta-1-my-findings/2368

**Comment by heartsentwined** [comment]
Thanks for the links, I'll digest them

**Comment by arronmabrey** [comment]
+1

**Comment by seifsallam** [comment]
@heartsentwined How is it going?

**Comment by heartsentwined** [comment]
In progress of a rather big refactoring, which is a pre-req for supporting all these divergent APIs of persistent libs. See [this comment](https://github.com/heartsentwined/ember-auth/issues/104#issuecomment-25064366).

**Comment by arronmabrey** [comment]
@heartsentwined Sounds awesome... lol.
Good luck and God Speed :-)

**Comment by seifsallam** [comment]
@heartsentwined wow! Best of luck man. Make ember-auth awesome :+1:

**Comment by sarjanen** [comment]
@heartsentwined do you have any solution for this or will Ember Auth die out? 
Edit, saw that you started with the injection pattern, good luck! Unfortunately I don't have the knowledge to help you.

**Comment by heartsentwined** [comment]
Yea, work is going on in the `injection` branch. Sorry the delay, we just shipped a project, I'm having more free time now :)

**Comment by arronmabrey** [comment]
@heartsentwined That's great to hear, shipping is the best. I'm in the middle of a project as well and can't wait until it's done so I can circle back to my side project that uses ember and and ember-auth. Seriously @heartsentwined thanks for your effort! I'm sure I can speak for everyone when I say, we are all very appreciative of your hard work :shipit:

**Comment by heartsentwined** [comment]
Thanks @arronmabrey I'll update you guys when it's ready

**Comment by jonnedeprez** [comment]
I've been able to use ember-auth in combination with Ember Data beta 2 without any problem.  

A bit hacky, but until an update of ember-auth is ready it works fine: I patched the findUser method by running this just after Auth is created (CoffeeScript):

``` javascript
App.Auth.get('_session').findUser = ->
  userId = @get('userId')
  auth = @
  if userId
    store = App.__container__.lookup("store:main")
    store.find('user', userId).then((user) -> auth.set('user', user))
```

To access the Auth object in controllers and routers I created an initializer with

``` javascript
application.register('auth:main', App.Auth,
    singleton: true
    instantiate: false
)
```

and one with

``` javascript
application.inject('controller', 'auth', 'auth:main')
application.inject('route', 'auth', 'auth:main')
```

In Handlebars you can then display the current user with `{{auth.user.fullName}}`. 
If you don't like the lookup of the store, you can of course also inject the store in the Auth object.

**Comment by heartsentwined** [comment]
Thanks for the ideas @jonnedeprez

**Comment by seifsallam** [comment]
@heartsentwined So ember-auth 9.0 is out :dancer: 

How can we integrate it?

**Comment by heartsentwined** [comment]
Give me some more time and the docs and upgrade guide will be out too :)

**Comment by seifsallam** [comment]
Thats awesome. Really appreciate your work here :)

**Comment by sarjanen** [comment]
+1 @seifsallam! But I still think you need to consider to enable a session to be active when a user reload the page, more user friendly. I have made a ugly hack but it's really ugly..

**Comment by heartsentwined** [comment]
@Padchi there's `rememberable` for that

**Comment by heartsentwined** [comment]
@Padchi I mean, unless you have some way to distinguish between "an immediate browser refresh" and "closing the browser and coming back visiting the same url after 5 days", I cannot see how that would be different from using the auto-recall feature from `rememberable`.

**Comment by sarjanen** [comment]
@heartsentwined true! But it's a pretty simple solution with sessionStorage.

**Comment by heartsentwined** [comment]
@seifsallam [docs](http://ember-auth.herokuapp.com/docs) updated! now give me yet more time for the changelog and upgrade guide. _Damn_ docs. Took me more time to write docs than `ember-auth` itself...

@Padchi `sessionStorage` - (something like `sessionRememberable`? I imagine it would be like `rememberable`, but using a session cookie as storage?) It sounds like a good idea for a module. Would you mind sharing what you have done? We can polish that for an `ember-auth` module.

**Comment by seifsallam** [comment]
@heartsentwined Awesome :) I can't though install other bower dependencies for jquery and the others

**Comment by heartsentwined** [comment]
@seifsallam sorry my bad, I forgot to register them in bower. I'll register them now.

**Comment by heartsentwined** [comment]
@seifsallam bower components all registered

**Comment by seifsallam** [comment]
Thanks. 

Isn't there an easier way than installing 8 packages and registering them? Its a good thing for the model adapter, but i think the defaults should be just packed in, is there a reason for why you extracted them?

**Comment by heartsentwined** [comment]
I weighed the cost and benefits of extracting them. Mainly -

> This should help keep your code size small. Now you will only include what you actually use in code base, not, e.g. the `dummy` adapters intended for unit-testing, or those modules that you don't use.
> 
> This should also allow you to pull in the latest upgrades, e.g. a BC Break on module A won't stop you from upgrade other parts - it would only trigger a major version bump on module A.

(extracted from the upgrade guide that I'm writing now)

The mass-installation is just a one-time cost for the dev, so it shouldn't be _that_ annoying.

I have also considered putting together a meta package, which includes the original defaults: `jquery` request adapter, `json` response adapter, `strategy` session adapter, `cookie` session adapter, and `emberData` module. But then, won't we want another meta package, e.g., for unit testing, that includes all the `dummy` adapters? Or is everybody already using `rememberable`, such that it should be included by default? I can't answer any of those questions satisfactorily, so I have decided against those meta packages.

How about an "everything" meta package, that includes _all_ the adapters and modules? Well, it would probably save some time for the dev, or serve as a starter kit. But then, I imagine that all devs would want to trim away the modules that they don't use prior to shipping anyway, which means they'd perform the mass-installation anyway.

**Comment by heartsentwined** [comment]
I have also read several blog posts (let's not name them directly) that complained about the bulky state of `ember-auth` - "I don't want a heavyweight code base just to authenticate a user". So I guess it's the right direction to go.

**Comment by seifsallam** [comment]
Ok, thanks for clearing that up

**Comment by heartsentwined** [comment]
Original issue (`ember-data` support) closed - `9.x` (latest version) now supports auto-loading current users for `ember-data` (also `epf` and `ember-model`). The usual code-generating [docs](http://ember-auth.herokuapp.com/) and [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide) to help with the transition.

Ticket left open, though, to track the `sessionRememberable` idea that popped up.

**Comment by sarjanen** [comment]
@heartsentwined it's nothing fancy. I just set a sessionStorage item with user's token and id when a user signs in and then checks after them in a simple initializer.

```
Ember.Application.initializer
    name: 'session'

    initialize: (container, application) ->
        App.Session = Ember.Object.extend(
             init: ->
                authToken = sessionStorage.getItem('authToken')
                authUserId = sessionStorage.getItem('authUserId')

                if authToken != null && authUserId != null
                    App.Auth.createSession '{"auth_token": "' + authToken + '", "user_id": "' + authUserId + '"}'
        ).create()

App.Auth.addHandler 'signInSuccess', ->  
    sessionStorage.setItem('authToken', App.Auth.get('authToken'))
    sessionStorage.setItem('authUserId', App.Auth.get('userId'))
```

**Comment by heartsentwined** [comment]
@Padchi so after a refresh, do you just "inject" back the auth session to `ember-auth` (probably via `createSession()`), or do you make a sign in request to the server with those credentials? The latter is similar to what `rememberable` does, but both would make sense.

**Comment by sarjanen** [comment]
@heartsentwined I just updated my post :)

**Comment by heartsentwined** [comment]
@Padchi Let's move discussion over to its own issue #109.

**Comment by heartsentwined** [comment]
Closing issue. The original `ember-data` support issue has been addressed with `9.x` release, and the discussion on the `sessionStorage` idea has been moved to #109.

**Comment by heartsentwined** [comment]
Thanks for the code sample @Padchi

**Comment by kirylrb** [comment]
@Padchi Hello! Could you describe how to use you initializer?

**Comment by sarjanen** [comment]
@kirylpl this project is dead and my code is long gone unfortunately. Check out ember-simple-auth or torii
