### ISSUE TITLE
AutoLoad User not working?

### ISSUE THREAD

**Issue by flynfish** [heartsentwined/ember-auth#104]
I upgrading to ember 1.0 and ember-auth latest. It doesn't look like the user is auto loaded anymore and I have to call it manually now:

I have it defined in auth.js:
`userModel: 'App.User',`

And I am logging in like so:

``` javascript
model.on('didCreateRecord', function() {
        var user = this._data;
        var auth = {auth_token: user.auth_token, user_id: user.id, remember_token: user.remember_token};
        App.Auth.createSession(auth);
        //App.Auth.get("user").reload(); have to uncomment this to reload the user. Before the user would just get loaded without me having to call this. .
      });
```

Is this intended behavior or should the user be autoloaded when calling `App.Auth.createSession()`?

**Comment by heartsentwined** [comment]
Are you on `ember-data >= 1.0`? That's a known case of not working for now.

**Comment by heartsentwined** [comment]
ref: #98 #102

**Comment by flynfish** [comment]
@heartsentwined no I am using ember-model latest version 0.0.10

**Comment by flynfish** [comment]
@heartsentwined I did some more testing, and it looks like the ember-model update from 0.0.9 to 0.0.10 broke this. I imagine its a similar issue to why its not working in ember-data.

**Comment by heartsentwined** [comment]
Ah, all these persistent libs, can't they adopt a common API? :sigh:

What is the canonical way of querying for a single record in ember-model at `0.0.10`? I mean the equivalent of `App.User.find(1)` / `store.find('user', 1)` / `session.load('user', 1)` / etc

**Comment by heartsentwined** [comment]
The current situation is that it is simply not-solvable with the current architecture. - You'll need userland code for now.

Previously, we could get away with a unified `App.User.find(id)`, being the common idiom of all three persistent libs.

`epf` was the first to break away from it, changing it to `session.load('user', id)`, but provides `App.User.find(id)` and `session.find('user', id)` for BC / ease of transition reasons, and (I think) you could pass `App.User` in place of `'user'` in all these places too.

Next `ember-data` broke away from this, and removed `App.User.find(id)` altogether in favor of `store.find('user', id)`. As far as I know calling `store.find(App.User, id)` won't work either.

Now it seems `ember-model` is breaking away from it to another API?

Why this is not solvable with the current API Is that `ember-auth` has no way of getting a copy of the application's `store` / `session` / whatever. It'll have to be refactored to use the injection pattern (#70) to permit injecting these into `ember-auth`, and selectively too, to cater for these divergent APIs.

**Comment by flynfish** [comment]
It uses .fetch for model and .find for adapter: 
`Model.fetch(<String|Number>)`\- find by primary key (multiple calls within a single run loop can coalesce to a findMany), returns a promise

``` javascript
Ember.Adapter = Ember.Object.extend({
  find: function(record, id) {}, // find a single record
  //more stuff
});
```

https://github.com/ebryn/ember-model/compare/0.0.9...0.0.10

**Comment by heartsentwined** [comment]
Ah, oh dear :-)

**Comment by heartsentwined** [comment]
So you should expect to pass `App.User` in, and have `ember-auth` call `App.User.fetch(id)`, right?

**Comment by flynfish** [comment]
Yes I think that is correct from my understanding/misunderstanding :confused:

**Comment by heartsentwined** [comment]
@flynfish the latest `ember-model` syntax now supported in `9.x`. The usual code-generating [docs](http://ember-auth.herokuapp.com/) and [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide) to help with the transition.

Snippet from the [docs](http://ember-auth.herokuapp.com/) for quick reference:

``` coffeescript
App.Auth = Em.Auth.extend 
  modules: ['emberModel']
  emberModel: 
    userModel: 'App.Member' # a string, not App.Member (the class)

# ember-auth will call App.Member.fetch(id)

# access the current user 
@auth.get('user')
```

Please reopen this ticket if it doesn't work.
