### ISSUE TITLE
Remember me not working when I reload the page

### ISSUE THREAD

**Issue by lukemarsh** [heartsentwined/ember-auth#106]
Hey, I've got an app using Devise for authentication but remember me doesn't seem to be working when I reload the page.

Any chance you could have a look through my code and see what the problem is?

https://github.com/lukemarsh/devicetracker

cheers!

**Comment by lukemarsh** [comment]
I am using ember auth. not just devise...

**Comment by heartsentwined** [comment]
@lukemarsh I'm quite busy these days, I'll get back when I have free time

**Comment by heartsentwined** [comment]
@lukemarsh https://github.com/lukemarsh/devicetracker gives me a `404` ... ?

**Comment by heartsentwined** [comment]
Closing since the referenced code `404`s - cannot debug further.
