### ISSUE TITLE
signedIn is false on signInSuccess event

### ISSUE THREAD

**Issue by guilemos** [heartsentwined/ember-auth#107]
hi guys, i'm starting with ember-auth to login users in my api.

I'm trying to load current user in signInSuccess, like this:

<code>App.Auth.on('signInSuccess', function() {
App.Auth.set('user', self.store.find('me')); <-- this call returns 401
});</code>

Calling my store in signInSuccess returns 401 cuz no token is sent.
I notice that "signedIn" is false during this event, so is set to true when event is ended.

Is there best place to load current user?

Thank you!!

**Comment by flynfish** [comment]
You can autoload the user by specifying the user model in auth.js -> 

``` coffeescript
App.Auth = Ember.Auth.create
  # ...
  userModel: 'App.User' # default null
  # pass the string, not a class App.User

# access the current user model
# as with all things ember, this is loaded asynchronously
App.Auth.get('user')
```

**Comment by guilemos** [comment]
Thanks for you reply!

I trying it cuz autoload don't working for me. Well, I take look in ember-auth.js and in my understand this function handles user's load:

<pre><code>  findUser: function () {
    var cache$, model, modelKey, this$;
    if (get$(this, 'userId') && (modelKey = get$(get$(this, 'auth'), 'userModel')) && (model = Ember.get(modelKey)))
      if (null != (null != (cache$ = set$(this, 'user', model.find(get$(this, 'userId')))) ? get$(cache$, 'then') : void 0)) {
        return model.find(get$(this, 'userId')).then((this$ = this, function (m) {
          return set$(this$, 'user', m);
        }));
      }
  }</code></pre>

My problem is the server don't return userId. Instead it, server return this:

<pre><code>{
access_token: "M2E2NmFkMWY2NDE2ZDFlZDJhYmFmM2ZiOTJiNTRjMGI1ZmViMTkxNzU0YzQ3YzZkZDk4NWY0NTY3NTY2ZGNkYg"
expires_in: 3600
refresh_token: "YjE0YzQ1OTJjNmUxMzY1ODJlOTViYzJlMDliMmJiNTlmYTZjZTcxODAwN2M2ZGFlYmU3YjlhM2U2MzFiZGQzOQ"
scope: null
token_type: "bearer"
}</code></pre>

There's way to autoload without userId?

**Comment by flynfish** [comment]
Does this help out?  [#63](https://github.com/heartsentwined/ember-auth/issues/63#issuecomment-18822827)

**Comment by guilemos** [comment]
I understand this approach, but I cannot see how it can help me, once that findUser method needs for a user_id to autoload user and I cannot provide it.

Or in my case I cannot use autoload?

Can you give me a sample?

Thank you!

**Comment by heartsentwined** [comment]
@guilemos @flynfish `9.x` (latest version) now supports auto-loading current users for `ember-data`, `epf` and `ember-model`. And without that bizzare hack with `.then()` checks and multiple calls. The usual code-generating [docs](http://ember-auth.herokuapp.com/) and [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide) to help with the transition.

Please reopen this ticket if it doesn't work.
