### ISSUE TITLE
Current User

### ISSUE THREAD

**Issue by AshesOfOwls** [heartsentwined/ember-auth#11]
I was wondering if there is a best practice for generating a current_user object or if in the future it would be possible to have it automatically generated under the Auth namespace.

Currently I am doing this...

``` coffeescript
App.ApplicationRoute = Ember.Route.extend
  init: ->  
    Auth.Module.RememberMe.recall()

    Auth.on 'signInSuccess', ->
      Auth.current_user = App.User.find(Auth.currentUserId)
```

There are some problems with this though, such as you can change the current user within the web inspector console so I need to watch for changes.

**Comment by heartsentwined** [comment]
Looks good, I'm trying to hack this feature at the moment.

---

Regarding your `current_user` manipulation concern: why, a user can actually manipulate the `currentUserId`, the `authToken`, and in fact everything in the ember app. My best advice is that we should treat ember apps as nothing more than a fancy UI for your server's API service. (Read [this FAQ](https://github.com/heartsentwined/ember-auth/wiki/Security#secure-server-side-api-code) for details.) Our users cannot read JSON, so we have built an ember app to "prettify" the JSON response for them.

Security should still happen in the server API end points themselves. What `ember-auth` does is only appending authentication tokens to API calls, and a couple of client-side authenticate state management helpers; it does not (and cannot, being a client-side implementation) provide security on its own.

For example, this code is dangerous:

``` html
<script type="text/x-handlebars">
  {{#if Auth.authToken}}
    hidden content
  {{else}}
    public content
  {{/if}}
</script>
```

The security hole is not on using `Auth.authToken` (or `Auth.currentUserId`, or anything for that matter) as the condition; it is the fact that a user can simply open your js files, and view `hidden content` directly.

Likewise, the server side API code should check for a valid `authToken` on every (protected) API end point access; if it checks only for a `current_user_id`, then the user can issue an API request separately and access all protected data, regardless of what happens in the ember app.

Just my two cents.

**Comment by heartsentwined** [comment]
This feature has been implemented in the latest version of `ember-auth`. Documentation at [readme](https://github.com/heartsentwined/ember-auth#auto-load-current-user-object), security notes at [wiki](https://github.com/heartsentwined/ember-auth/wiki/Security#current-user), but a brief summary for your use case here:

``` coffeescript
Auth.Config.reopen
  userModel: App.User
```

Access the user model via `Auth.currentUser` in handlebars, or `Auth.get('currentUser')` in js. For consistency with the rest of the module, it is a camel cased `currentUser`, not an underscore cased `current_user`.

**Comment by AshesOfOwls** [comment]
Thanks!

**Comment by kersten** [comment]
Many thanks for this, will check it in a couple of days.
