### ISSUE TITLE
@auth.send is not working correctly

### ISSUE THREAD

**Issue by seifsallam** [heartsentwined/ember-auth#111]
I can't get `@auth.send` to be working like it used to before. I've updated ember-auth to `v9.0.6`. But it doesn't read any of the settings below.

I've tried `Ember.$.ajax` and its sending everything correctly, but of course without the `auth_token`. Any ideas what i'm doing wrong?

``` coffee
App.UsersController = Ember.ArrayController.extend(
  actions:
    follow: (user) ->
      if @auth.get 'signedIn'
        @auth.send
          url: "#{BASE_URL}/users/#{user.id}/follow"
          type: 'POST'

    unfollow: (user) ->
      if @auth.get 'signedIn'
        @auth.send
          url: "#{BASE_URL}/users/#{user.id}/follow"
          type: 'DELETE'

)
```

**Comment by heartsentwined** [comment]
Oh yes, I discovered today that two bugs affecting `@auth.send` slipped through. Does these two fixes address your problem?
- https://github.com/heartsentwined/ember-auth/commit/397d87447e652c6b2da69c7e9649c5f95b816b4d (released in `ember-auth` `9.0.6`)
- https://github.com/heartsentwined/ember-auth-request-jquery/commit/10c8813699e1c9257c69f36ac8f697dcc280297f (released in `ember-auth-request-jquery` `1.0.3`)

**Comment by seifsallam** [comment]
Fixed. Totally forgot to update `request-jquery`, my bad.

**Comment by heartsentwined** [comment]
Actually my bad, those mistakes shouldn't have creeped into releases. Sorry, sorry for the troubles.
