### ISSUE TITLE
get$(this, '_request') is Undefined

### ISSUE THREAD

**Issue by guilemos** [heartsentwined/ember-auth#112]
Hello guys, I'm upgrading to new version and I'm having the follow issue when I try to signIn:

Uncaught TypeError: Cannot call method 'resolveUrl' of undefined in this line:

<code>76. url = get$(this, '_request').resolveUrl(get$(this, 'signInEndPoint'));</code>

on debug, get$(this, '_request') returns undefined. Any ideias?

Regards!

**Comment by heartsentwined** [comment]
Any more code for debugging the issue?

**Comment by heartsentwined** [comment]
Also, can you post the output of `App.__container__.lookup('authRequest:jquery')`? (replace `App` with your app name, and probably `jquery` with `dummy` if you are using the dummy request adapter)

**Comment by guilemos** [comment]
@heartsentwined, App.**container**.lookup('authRequest:jquery') returns undefined too.

My code is simple:

``` javascript
App = Ember.Application.create();
App.Auth = Em.Auth.extend({
    baseUrl: 'http://www.api.localhost:91/',
    session: 'cookie',
    request: 'jquery',
    signInEndPoint: Routing.generate('bw_user_signin'),
    signOutEndPoint: Routing.generate('bw_user_signout'),
    modules: ["emberData", "authRedirectable", "actionRedirectable", "rememberable", "timeoutable"],
    tokenKey: 'access_token',
    emberData: {
        userModel: 'me',
    },
    authRedirectable:{
        route: 'index'
    },
    actionRedirectable:{
        signInRoute: 'home',
        signOutRoute: 'index',
        signInSmart: true,
        signInBlacklist: ['register', 'sign-in', 'index'],
    },
    rememberable: {
        tokenKey: 'refresh_token',
        period: 14 ,
        autoRecall: true,
    },
    timeoutable: {
        period: 60,
    },
});
```

in my controller action:

``` javascript
            this.auth.signIn({
                data: {
                'username': this.username,
                'password': this.password,
            }});
```

Thank you!

**Comment by heartsentwined** [comment]
Have you included the `ember-auth-request-jquery` file (and others)? The equivalent code for `rails` is

``` coffeescript
# application.coffee 
# ... 
#= require ember-auth 
#= require ember-auth-request-jquery
```

I'm not a user of other envs or build tools, so I cannot provide any canonical example for other environments.

**Comment by guilemos** [comment]
Yep, you're right! My bad... It's works now!

Thank you! Great job!

**Comment by heartsentwined** [comment]
I have added a reminder on the docs about including files though, thanks for the issue!

**Comment by ekampp** [comment]
I have included th `ember-auth-request-jquery` library, and I still get this error.

**Comment by ekampp** [comment]
Never mind. I can't spell :)

**Comment by heartsentwined** [comment]
@ekampp so it's just a typo?

**Comment by ekampp** [comment]
Yes, and I can't read either.
