### ISSUE TITLE
Update docs - rememberable requires session 

### ISSUE THREAD

**Issue by flynfish** [heartsentwined/ember-auth#114]
In the process of upgrading to `.9.x` and tried adding the rememberable module without also including the `ember-auth-session-cookie`, so an undefined error is thrown. 

Would be good to make a note in the docs that `rememberable` requires a `session strategy` to work correctly.

**Comment by heartsentwined** [comment]
A `session` is compulsory actually, it is where `ember-auth` holds auth information. Previously it was still there, just configured to be `cookie` by default so "hidden" from userland code.

**Comment by flynfish** [comment]
Ok I understand now.... but it isn't clear that its compulsory in the session section of the docs. It makes sense when you think about it of course :), but someone new reading the docs might not know since it doesn't explicitly say it anywhere. (unless I just missed that part)

**Comment by heartsentwined** [comment]
I'll clarify it in the docs, thanks for the issue!

**Comment by heartsentwined** [comment]
This has been added to the [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide). The expectation should be limited to users of previous `ember-auth` versions. The [docs](http://ember-auth.herokuapp.com) themselves treat all adapters equally, presenting them one by one at the top, so there shouldn't be a case where any particular one will be taken as "optional".
