### ISSUE TITLE
@auth.signIn() not resolving the promise

### ISSUE THREAD

**Issue by ekampp** [heartsentwined/ember-auth#116]
Hi there. 

It seems, that when running `@auth.signIn()` the returned promise object doesn't resolve properly. 

I would expect the following to resolve the `then` function.

``` coffee
sign_in = @auth.signIn
  data:
    user:
      username: @get('username')
      password: @get('password')
sign_in.then =>
 console.log "hello.."
```

The server is responding with the following JSON, which should be quite correct? 

``` json
{
  "auth_token": "abc123",
  "user_id": 1
}
```

**Comment by flynfish** [comment]
@ekampp are you using ember-data or ember-model?

**Comment by ekampp** [comment]
Ember data, why?

**Comment by flynfish** [comment]
Just curious since I am using ember-model and was running into similar issues and wasn't sure if it might have been the ember-model module.

**Comment by ekampp** [comment]
Ahh. No, I'm using ember data. And the problem here, as opposed to #115 is that the ember promise isn't resolved. The server responds 200 OK, but the promise isn't fulfilled.

**Comment by ekampp** [comment]
After some investigation, it turns out, that this is an issue with the local-storage mixin. Since changeing to cookie, correctly resolves the promise. 

Poking about the code, it seems that the `_session` set on the Auth object is undefined, when using the `local-storage` mixin. I think, that maybe something in the initialisation of that object is off?

**Comment by heartsentwined** [comment]
@ekampp can you give me the output of

``` javascript
App.__container__.lookup('authSession:localStorage')
```

when you are using the `localStorage` `session` adapter?

**Comment by heartsentwined** [comment]
I can't reproduce the issue, but at least it shouldn't be related to whether the `session` adapter is `cookie` or `localStorage`. I dropped this into the [demo app](https://github.com/heartsentwined/ember-auth-rails-demo)

``` coffeescript
EmberAuthRailsDemo.AuthSignInController = Em.Controller.extend
  email: null
  password: null
  remember: false

  actions:
    signIn: ->
      @auth.signIn(
        data:
          email:    @get 'email'
          password: @get 'password'
          remember: @get 'remember'
      ).then =>
        console.log 'signed in' # here
```

And it reached `console.log` both when using the `cookie` or `localStorage` adapters.

**Comment by ekampp** [comment]
Hmm.. I will try and investigate this further. Since I don't mind using the cookie (session) store, I will close this. We can reopen, if I find more information.

**Comment by somebody32** [comment]
Have the same problem here, changing store to `cookie` also resolved this

**Comment by ekampp** [comment]
@somebody32 did you have any settings, that you are specifically aware of, which could defer from the ones used by  @heartsentwined

**Comment by somebody32** [comment]
@ekampp all are very basic ones:

``` coffee
App.Auth = Ember.Auth.extend
  signInEndPoint: 'auth/sign_in'
  signOutEndPoint: 'auth/sign_out'

  # session: "local-storage"

  strategy: 'token'
  tokenKey: 'auth_token'
  tokenLocation: 'param'

  modules: ['ember-data', 'rememberable']

  rememberable:
    tokenKey: 'remember_token'
    period: 7
    autoRecall: true

```

**Comment by ekampp** [comment]
I don't have any special settings either, but I can't quite pinpoint the problem, other than the local-storage isn't initialised. It seems to be null, when debugging the code.

**Comment by davewasmer** [comment]
+1 same issue I think.

My sign in call (`@auth.signIn(data: credentials)`) seemed to lead to an "Invalid JSON" error (once I enabled console.assert on Ember.RSVP[1]).

I stepped through in the inspector:

``` javascript
// line 83, ember-auth.js
return get$(this$, '_request').signIn(url, get$(this$, '_strategy').serialize(opts)).then((this$1 = this$, function (response) {
  // ...
  promises.push(get$(this$1, '_strategy').deserialize(data)); // line 87
```

which led to:

``` javascript
deserialize: function (data) {
  set$(this, 'authToken', data[get$(get$(this, 'auth'), 'tokenKey')]);
  if (get$(get$(this, 'auth'), 'tokenIdKey'))
    return set$(get$(get$(this, 'auth'), '_session'), 'userId', data[get$(get$(this, 'auth'), 'tokenIdKey')]);
                                        //  ^ this.auth._session is undefined here
}
```

Here is the ember-auth object:

``` coffeescript

App.Auth = Ember.Auth.extend

  request: 'jquery'
  response: 'json'

  strategy: 'token'
  tokenKey: 'auth_token'
  tokenLocation: 'authHeader'
  tokenHeaderKey: 'AUTH-TOKEN'
  tokenIdKey: 'user_id'

  session: 'local-storage'

  signInEndPoint: '/api/sign-in'
  signOutEndPoint: '/api/sign-out'

  modules: [ 
    'emberData'
    'authRedirectable'
    'actionRedirectable'
  ]

  emberData:
    userModel: 'user'

  authRedirectable:
    route: 'sign-in'

  actionRedirectable:
    signInRoute: 'index'
    signInSmart: 'true'
    signInBlacklist: [
      'sign-up'
      'sign-in'
    ]
    signOutRoute: 'index'
```

Let me know if it would helpful to provide any other detail, or if I can help out in any other way.

[1] https://github.com/tildeio/rsvp.js/blob/master/README.md#error-handling

**Comment by conrad-vanl** [comment]
I'm getting the same issue...

**Comment by bugduino** [comment]
Anyone has solved this issue?
