### ISSUE TITLE
Grabbed user varies after transition event

### ISSUE THREAD

**Issue by ekampp** [heartsentwined/ember-auth#118]
Grabbing the user through `@auth.get('user')`. Then transition route, and grab the user again through `@auth.get('user')` returns different results. 

I have a backend, which returns the following JSON:

``` JSON
{
  "id": 1,
  "username": "bob",
  "type": "UserAdmin"
}
```

And a model to reflect this:

``` coffeescript
User = DS.Model.extend
  type: DS.attr('string')
  username: DS.attr('string')
```

The signing in through `@auth.signIn()` and then grabbing the user through `@auth.get('user')`, the type is correctly reflected. 

Then when transitioning to another route, and switching an if-else case on the type, it has suddently reverted to `null`. 

I believe the information about the user is cached in the store layer, and thus, it seems that the retrieved data isn't written correctly to the user record when a user object is initially fetched.

Does anybody have any ideas?

**Comment by heartsentwined** [comment]
Among all the `ember-auth` adapters and modules, the `auth.user` setter is only called on two occasions:
- post-sign in auto-load user on all three persistence libraries, if auto-loading is enabled 
- post-sign out clearance of session data

If it gets called during a normal `transitionTo`, the it is definitely a bug. However, the public api (`auth.get('user')`) is itself a computed property, and I suspect that userland code may go through some more layers of computed properties too - things might go wrong in one of these.

Could you post more context on the `@auth.get('user')` call?

**Comment by ekampp** [comment]
I will look into this, I just haven't had the time.
