### ISSUE TITLE
Get current user in Ember.Object

### ISSUE THREAD

**Issue by sarjanen** [heartsentwined/ember-auth#119]
Is this possible? Maybe if we inject auth into model?

**Comment by heartsentwined** [comment]
Inject `auth:main` into wherever you want to use it.

``` coffeescript
App.Foo = Em.Object.extend
  init: ->
    @_super()
    console.log @auth.get('user')
```

``` coffeescript
Em.onLoad 'Ember.Application', (app) ->
  app.initializer
    name: 'injectFoo'

    initialize: (container, application) ->
      application.register 'foo:main', App.Foo

      # ah well, you might want to inject foo elsewhere too
      application.inject 'controller', 'foo', 'foo:main'
      application.inject 'route',      'foo', 'foo:main'

      # inject auth here
      application.inject 'foo',        'auth', 'auth:main'
```

**Comment by sarjanen** [comment]
"Uncaught TypeError: Cannot call method 'get' of undefined" What have i done wrong?

``` CoffeeScript
Ember.onLoad 'Ember.Application', (app) ->
    app.initializer
        name: 'injectPermission'

        initialize: (container, application) ->
            application.register 'permission:main', App.Permission

            # ah well, you might want to inject foo elsewhere too
            application.inject 'controller', 'permission', 'permission:main'
            application.inject 'route',      'permission', 'permission:main'

            # inject auth here
            application.inject 'permission','auth', 'auth:main'
```

``` CoffeeScript
App.Permission = Ember.Object.extend
    init: ->
        @_super()
        console.log @auth.get('user')
```

Console just log "null"

**Comment by heartsentwined** [comment]
My apologies, I forgot one potentially crucial line:

``` coffeescript
# ...
  app.initializer
    name: 'injectPermission'
    after: 'ember-auth' # !!!
# ...
```

Let me know if this solves the problem.

**Comment by sarjanen** [comment]
@heartsentwined sorry but I still get the same error message?

**Comment by heartsentwined** [comment]
Any more code, or a js fiddle, for debugging?

**Comment by sarjanen** [comment]
Well, there is no more code. I have commented out everything else just to get this working. Before 9.x I hade somthing like this and that worked:

``` CoffeeScript
App.Permission = Ember.Object.extend        
    content: null
    currentUserBinding: "App.Auth.user"

App.Permissions =
    _perms:    {}
    register: (name, type)  -> @_perms[name] = type
    get:            (name, attrs) -> @_perms[name].create(attrs)
    can:            (name, attrs) -> @get(name, attrs).get("can")

App.Permissions.register "editUser", App.Permission.extend
    can: (->
        return false unless @get("currentUser")
        @get("currentUser.roles").contains('admin') || @get("content.id") == @get("currentUser.id")
    ).property("currentUser", "content")
```

But this seems irrelevant because I commented out everything else except App.Permission just to try to get it to work.

**Comment by heartsentwined** [comment]
It looks like your second `App.Permissions` definition has overridden the first `Em.Object.extend()` definition. Hence the `App.Permissions` object isn't really an `Em.Object`, just a plain javascript object. Therefore, no ember-specific injections can occur.

I would implement it like this:

``` coffeescript
# define the permissions object
App.Permissions = Em.Object.extend
  register: -> # something
  can: -> # blah
  currentUser: Em.computed.alias 'auth.user'
  # note that all of those are *instance* methods, not *class* methods

# inject a permissions object to, e.g. routes
Em.onLoad 'Ember.Application', (app) ->
  app.initializer
    name: 'injectPermissions'
    after: 'ember-auth'

    initialize: (container, application) ->
      application.register 'permissions:main', App.Permissions
      # or singleton - see comment below
      # application.register 'permissions:main', App.Permissions, {singleton: true}

      application.inject 'route', 'permissions', 'permissions:main'
      # inject auth
      application.inject 'permissions', 'auth', 'auth:main'

# somewhere in routes 
App.SecretRoute = Em.Route.extend
  activate: ->
    # access permissions object with this.permissions too
    @permissions.register() # something
```

You may want to read up on [bindings being _quietly_ deprecated](http://stackoverflow.com/a/18523034/2360942) in favor of CPs, and the [injection pattern](http://mcdowall.info/posts/ember-application-initializers/). Depending on your use case, you might want to make `App.Permissions` a `singleton` (`auth` is a singleton).

**Comment by heartsentwined** [comment]
However, if you don't want to change the structure of your old code, you can always grab a copy of anything injected in the container via

``` coffeescript
App.__container__.lookup('auth:main') # or another key
```

This would work globally, because the `App` object itself is a global object. But this is, of course, not intended to be a public API. Use at your own risk.

**Comment by heartsentwined** [comment]
It's pretty much the same story: avoid global object, having cleaner objects fetched through the container, which proxies through to the declared factories. This happened in `ember-auth` from `8.x` to `9.x`, and you might recognize the same with `ember-data` going from

``` coffeescript
App.Foo.find(1)
```

to

``` coffeescript
# in a route, a controller, or somewhere with store injected
@store.find('foo', 1)
```

... unless you were not around when `ember-data` was still in the old version...

**Comment by heartsentwined** [comment]
Final note: the previous version worked because `App.Auth` itself was global code. Previously the declaration was 

``` coffeescript
App.Auth = Em.Auth.create() #  ...
```

Thus there was a global instance of `ember-auth` directly at `App.Auth`, so it would work even if you have bypassed ember's injection mechanism.

**Comment by sarjanen** [comment]
Oops, this is where suddenly a little bit too advanced for me. The code above is not mine, but a simple copy and paste from http://livsey.org/blog/2012/10/16/writing-a-helper-to-check-permissions-in-ember-dot-js/ 

Guess I'll try to come up with another solution. 
And i have tried the lookup "hack" but it didn't work. I guess it's because my second permission. But did you notice that it's Permisson and PermissonS? Maybe that dosen't matter.

**Comment by heartsentwined** [comment]
Doesn't matter whether it is singular or plural, as long as you use the same form consistently throughout.

**Comment by sarjanen** [comment]
Ok. Close this one then, my problem :)

**Comment by heartsentwined** [comment]
I'll put a mini-tutorial here nevertheless, typing right now...

**Comment by heartsentwined** [comment]
The whole idea of injection is actually pretty simple once you boil it down to the basics. Let's assume you want a global container object for permission (we'll use singular here), and that it will be a singleton.

(1) Declare the object.

Just in case you are wondering where to put them: I have put these helper objects under `helpers/`, and I require them before routes, controllers, etc.

``` coffeescript
# define the permissions object
App.Permission = Em.Object.extend
  init: -> # do bootstrap work if you like

  currentUser: Em.computed.alias 'auth.user'

  register: -> # something
  can: -> # blah
```

(2) Declare an initializer, register the object, and declare (inject) its dependencies.

Similar, I have put these all under `initializers/`, and require them early as above.

``` coffeescript
# inject a permission object to, e.g. routes
Em.onLoad 'Ember.Application', (app) ->
  app.initializer
    name: 'injectPermission'
    after: 'ember-auth'

    initialize: (container, application) ->
      # this line registers the permission object,
      # so that you can lookup() it in the container
      # we want a singleton in this example
      application.register 'permission:main', App.Permission, {singleton: true}
      # signature:
      # application.register key, factory, opts

      # inject it into routes,
      # so that you can grab a copy of the object *instance*
      # in all routes via this.permission
      application.inject 'route', 'permission', 'permission:main'
      # signature:
      # application.inject targetKey, propertyName, objectKey
      #   - targetKey = destination of where you want to inject to
      #     note that a "blank" key (without ":" part) means ":main"
      #   - propertyName = 'foo' will let you access this via this.foo
      #   - objectKey = same key as we registered above

      # inject other dependencies, here we inject auth
      # - as mentioned, this means inject to "permission:main"
      application.inject 'permission', 'auth', 'auth:main'
```

(3) Access the object via `this.name` as declared above

``` coffeescript
# in a route
App.FooRoute = Em.Route.extend
  someMethod: ->
    @permission # okay
    @permission.auth # okay *note
    # *note or is it @permission.get('auth') ?
    # sorry I'm too used to emberscript magic

# somewhere else, e.g. in a controller
App.FooController = Em.Controller.extend
  someMethod: ->
    @permission # nope
    # because we have not injected permission to a controller
```

**Comment by heartsentwined** [comment]
@Padchi Mini-tutorial up. Hope it helps.

**Comment by heartsentwined** [comment]
As for the `binding`, just replace all `binding`s with `Em.computed.alias()` calls, as illustrated above. That's a _one-way_ computed property, but it is rare that you really want _two-way_ bindings. A two-way binding can be manually setup with an observer that changes the original value where appropriate.

So far I have only encountered a single use case where I want a two-way binding, and that is binding value from a user input field. So I have setup observers on `keyUp`, `focusOut` events, etc, that would call `set()` on the original value.

**Comment by sarjanen** [comment]
Yeah it's a bit clearer now. I'm still confused about how i will register new permissons like "editUser" so I can use them in a "can" helper. The original code was so I can use a can helper like this {{#can editUser}}{{/can}} to show/hide some content for users in a template. 
All this haven't been necessary if I just could pass arguments to handlebars if helper...

Maybe a way to check some permissions in a template would be nice in a module. But on the other hand, it would destroy the gems simplicity.

Thanks by the way! I really appreciate your mini tutorial.

**Comment by heartsentwined** [comment]
I haven't had time to check and digest the full implementation at the original blog yet, perhaps someone else can help you in the meantime?

I have considered a module like `canCan` support, but I have decided against it, because there is no standard on how to pass permissions in user APIs. Typically this would be very use-case specific. perhaps the user model would return `isModerator`, `isAdmin` flags, or maybe a `role` field, or maybe even a `date` field `allowedToEditUntil` etc. Then the bulk of the logic would still live in userland code anyway, with anything from a simple `isAdmin` check, to whatever complex logic.

A simple implementation that "just works" would be defining boolean flags on the user model itself (or maybe a controller), and use them in handlebars with `{{#if}}`. e.g.

``` coffeescript
App.User = DS.Model.extend
  isAdmin: DS.attr 'boolean'

  canEdit: (->
    @get('isAdmin')
  ).property('isAdmin')
```

```
{{#if user.canEdit}}
  blah
{{/if}}
```

**Comment by sarjanen** [comment]
Yeah that would be too complex.

I don't to like simply check if a user is a admin or not because a user should be able to edit his or hers own post. I saw your edit, I guess that @get('post.user') didn't work?

**Comment by heartsentwined** [comment]
No, I took that out to simplify the example. A more logical example would involve defining a `canEdit` property on the `post` itself, proxying back to its `belongsTo` `user` model. But showcasing that would complicate things.

**Comment by sarjanen** [comment]
Ok! Well its seems like i need to search for my answer somewhere else, thanks for your help!
