### ISSUE TITLE
Redirect unauthorized routes not working

### ISSUE THREAD

**Issue by joscas** [heartsentwined/ember-auth#12]
I have the following route:

BaseApp.UsersIndexRoute = Auth.Route.extend({
  model: function() {
    return BaseApp.User.find();
  },
  setupController: function(controller, model) {
    controller.set('users', model);
    return this.controllerFor('application').set('currentRoute', 'users');
  }
});

And the following Auth file:

Auth.Config.reopen({
  tokenCreateUrl: '/users/sign_in',
  tokenDestroyUrl: '/users/sign_out',
  tokenKey: 'auth_token',
  idKey: 'user_id',
  rememberMe: true,
  rememberTokenKey: 'remember_token',
  rememberPeriod: 7,
  signInRoute: 'sign_in',
  authRedirect: true,
  signInRedirectFallbackRoute: 'home',
});

The whole application can be found here:
https://github.com/joscas/base_app

When I acces 'localhost:3000/users' without login, the application is not redirected to 'sign_in' but I think it should be redirected because it inherits from Auth.Route

**Comment by ebastien** [comment]
My understanding is that the model hook of the route gets called before attempting the redirect.
Trying to load the model without being authenticated fails and it somehow prevents the redirect to complete.
You could try checking Auth.authToken before loading your model to see if it solves your problem.

**Comment by joscas** [comment]
@ebastien I've tried what you suggest but Ember attempts to load the model always. No matter what I do inside the model call. For example this doesn't work:

BaseApp.UsersIndexRoute = Auth.Route.extend({
  model: function() {
    var model = (Auth.authToken) ? BaseApp.User.find() : null;
    return model;
  },
  setupController: function(controller,model) {
    controller.set('users', model); 
    return this.controllerFor('application').set('currentRoute', 'users');
  }
});

But this doesn't work either:

BaseApp.UsersIndexRoute = Auth.Route.extend({
  model: function() {
  },
  setupController: function(controller,model) {
    controller.set('users', model); 
    return this.controllerFor('application').set('currentRoute', 'users');
  }
});

It still tries to access /users in the rails backend without token. Isn't that strange?

Started GET "/users" for 127.0.0.1 at 2013-03-22 16:09:18 +0100
Processing by UsersController#index as HTML
Filter chain halted as :auth_only! rendered or redirected
Completed 401 Unauthorized in 0ms (Views: 0.2ms)

**Comment by joscas** [comment]
I found this solution. I do a redirect in the rails controller when the user is not authorized:

  def auth_only!
    unless params[:auth_token] && user_signed_in?
      #render json: {}, status: 401
      redirect_to "/sign_in"
    end
  end

Not sure if this is still a bug or the expected behavior.
To clarify, the problem is that trying to access /users directly produces an access to the API always and when rails responds with 401 there is no redirection despite the route inheriting from  Auth.Route

**Comment by joscas** [comment]
Actually I think this is the expected behavior. JS can't do any redirection if it hasn't been loaded yet... I close this
