### ISSUE TITLE
Reusing RestAdapter's ajax method

### ISSUE THREAD

**Issue by iHiD** [heartsentwined/ember-auth#14]
Hey. This is a brilliant plugin. Thanks!

I'm using JSONP for my API and so have a slightly custom ajax function in my adapter. Ember-auth uses it's own (which seems to basically be a copy of the RestAdapter's), so I was wondering if it would make sense just to call that, rather than have the duplication.

In my code I'm currently doing the following, which works a treat:

```
Auth.reopen
  ajax: (url, type, hash) -> App.store.adapter.ajax(url, type, hash)
```

I imagine other people will have custom ajax methods, especially for the JSONP stuff, so it might be a worthwhile thing to do. 

The current AJAX method is here: https://github.com/heartsentwined/ember-auth/blob/master/lib/ember-auth.js#L107

Thanks again!

**Comment by heartsentwined** [comment]
The reason why I duplicated the method is a chicken-and-egg problem. I cannot call the original adapter's ajax method until it is initialized, and I need to know the application namespace (not everybody will call it `App`) in order to resolve to the instance. And `ember-auth` is loaded before the store is initialized, as in this code:

``` coffeescript
App.Store = DS.Store.extend # still extending here only..
  adapter: Auth.RESTAdapter.create() # a create, not an extend
```

I hate the duplication too, and I would very much like to do it your way if possible.

Indeed this chicken-and-egg problem is present almost everywhere throughout `ember-auth`. I wish there would be a dynamic call that resolves to the application namespace, or something like that, but I do not know of any at present.

**Comment by heartsentwined** [comment]
Alternatively, we can find a way to implement a decorator-style ajax call. The one in `ember-data` is hard-coded with their own needed variables; then you need to overwrite the whole method to implement your custom logic (you probably duplicate some of the original functionalities in your custom ajax method?). And still then `ember-auth` wants to inject the authentication token, or perhaps another authentication method as in #10 .

This probably belongs to the domain of `ember-data` though.

**Comment by iHiD** [comment]
Yeah - I see the problem. That namespace issue is a bit of a killer generally (my namespace is Medudcation, not App, so it would apply directly to me). I'll have a think and get back to you if I come up with anything.

**Comment by heartsentwined** [comment]
The `3.0` branch introduces a new `Auth.ajax` method, that will allow for userland overrides. Basically, it allows you to override whatever params passed to `jQuery.ajax(settings)` in userland code. If you need additional logic, you can also put it in your override function.

The corresponding ajax method from `ember-data` should have been built this way in the very first place, but well, at least you can do it here before I can get an PR accepted over there.

BC Breaks and upgrade guide for `3.0` branch available in the [Changelog](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md).

Full relevant readme section:

> ## Customize ajax calls
> 
> `Auth.ajax` is the central handler for all API calls, including those
> generated by `ember-data`, `ember-auth`'s native authentication API calls,
> and it is also available for any custom API calls. It ultimately delegates to
> `jQuery.ajax(settings)`, and all preset options are overridable by supplying
> your own options.
> 
> Function signature:
> 
> ``` coffeescript
>   # @param {settings} jQuery.ajax options
>   #   Defaults will be overrided by those set in this param
>   ajax: (settings) ->
> ```
> 
> Example override:
> 
> ``` coffeescript
> Auth.reopen
>   ajax: (settings) ->
>     settings.contentType = 'foo'
>     @_super settings
> ```
> 
> All ajax calls will now be made with `contentType` set to `foo`, overriding
> the default `application/json; charset=utf-8`.
