### ISSUE TITLE
Auth.Route.extend() not working

### ISSUE THREAD

**Issue by masood09** [heartsentwined/ember-auth#22]
When using Auth.Route.extend() I am getting an error Error: assertion failed: The route null was not found.

The Em.Route.extend() is working fine.

I am running ember-1.0.0-rc2

Let me know what's causing this. Attaching the code below.

``` coffeescript
App = Em.Application.create
    LOG_TRANSITIONS: true

Auth.Config.reopen
    tokenCreateUrl: '/user/sign_in'
    tokenDestroyUrl: '/user/sign_out'
    tokenKey: 'auth_token'
    idKey: 'user_id'
    authRedirect: true
    signInRedirectFallbackRoute: 'index'

App.Store = DS.Store.extend
    revision: 11 # or whatever suitable
    adapter: Auth.RESTAdapter.create()

App.Router.map ->
    @route 'sign_in'
    @route 'test'

App.IndexRoute = Em.Route.extend
    model: ->
        ['red', 'yellow', 'blue']

App.TestRoute = Auth.Route.extend()

App.SignInRoute = Em.Route.extend()

App.SignInController = Auth.SignInController.extend
    email: null
    password: null

    signIn: ->
        @registerRedirect()
        Auth.signIn
            email:    @get 'email'
            password: @get 'password'
```

**Comment by heartsentwined** [comment]
I haven't duplicated the code to test yet, but at first glance, `Auth.Config.signInRoute` is missing.

If you are using `Auth.Config.authRedirect = true`, then you also need to define `Auth.Config.signInRoute`. The latter specifies where to redirect the non-signed-in user when one accesses the `Auth.Route`:

> ### Authenticated-only routes
> 
> You can have non-authenticated ("not signed in") users redirected to a sign in route - let's say, named sign_in - when they visit an Auth.Route:
> 
> ``` coffeescript
> Auth.Config.reopen
>   signInRoute: 'sign_in'
>   authRedirect: true
> ```

The `Auth.Config.signInRedirectFallbackRoute` is for another redirect:

> ### Post- sign in redirect: fixed route
> 
> You can have the user redirected to a specified route - let's say, 'account' - after signing in.
> 
> ``` coffeescript
> Auth.Config.reopen
>   signInRedirectFallbackRoute: 'account' # defaults to 'index'
> ```

Let me know if the problem persists.

**Comment by heartsentwined** [comment]
This issue has been closed and reopened almost immediately. A wrong click? Or has anything resurfaced? @masood09

**Comment by masood09** [comment]
Wrong click sorry! Will be checking the solution posted by you in an hour or so and update the issue status accordingly.
—

**Comment by heartsentwined** [comment]
No problem, take your time!

**Comment by masood09** [comment]
Thanks! The solution worked. Should have read the README file carefully.
