### ISSUE TITLE
Persistence adapter not authenticating after upgrade

### ISSUE THREAD

**Issue by joscas** [heartsentwined/ember-auth#25]
I have updated my application to the last ember-auth release and my authenticated routes have stopped to work. Maybe there's a breaking change that I haven't taken into account but I can't find it.

My application is here: https://github.com/joscas/base_app

For example, when I try to acces the UsersIndexRoute, before I could see that ember was adding auth_token to the request:

GET "/users?auth_token=oShTL76ZkpFm1vrU8bVg"

But now the auth_token is gone when I access this route.

This is the route:

BaseApp.UsersIndexRoute = Auth.Route.extend({
  model: function() {
    return BaseApp.User.find();
  },
  setupController: function(controller,model) {
    controller.set('users', model);
    return this.controllerFor('application').set('currentRoute', 'users');
  }
});

This is my store.js

BaseApp.Store = DS.Store.extend({
  revision: 11,
  adapter: Auth.RESTAdapter.create()
});

**Comment by heartsentwined** [comment]
Thanks for the bug report, I'll look into it.

**Comment by joscas** [comment]
Many thanks. Please let me know if I can provide additional information.

**Comment by heartsentwined** [comment]
This took longer than I expected because there are a myriad of circumstantial factors that could affect `Auth.ajax`, mostly introduced by the new customizable `Auth.ajax` functionality. Anyway, it should be fixed in the new `ember-auth-source = 3.0.3` build.

**Comment by joscas** [comment]
Thanks for fixing but I've upgraded and now when I access the route I get this error:

Uncaught TypeError: Cannot read property 'auth_token' of null ember-auth.js:229
window.Auth.evented.create.ajax ember-auth.js:229
Auth.RESTAdapter.DS.RESTAdapter.extend.ajax ember-auth.js:328
superWrapper ember.js:947
DS.RESTAdapter.DS.Adapter.extend.findAll ember-data.js:7791
DS.Store.Ember.Object.extend.fetchAll ember-data.js:1647
DS.Store.Ember.Object.extend.findAll ember-data.js:1634
DS.Store.Ember.Object.extend.find ember-data.js:1324
(anonymous function) ember-data.js:3840
BaseApp.UsersIndexRoute.Auth.Route.extend.model index_route.js:4
superWrapper ember.js:947
Ember.Route.Ember.Object.extend.deserialize ember.js:23737
Router._paramsForHandler ember.js:22776
doTransition ember.js:22908
Router.transitionTo ember.js:22677
doTransition ember.js:23552
Ember.Router.Ember.Object.extend.transitionTo ember.js:23415
Ember.LinkView.Ember.View.extend.click ember.js:24262
Ember.CoreView.Ember.Object.extend.trigger ember.js:14181
superWrapper ember.js:947
Ember.merge.handleEvent ember.js:16670
Ember.View.Ember.CoreView.extend.handleEvent ember.js:16160
(anonymous function) ember.js:13925
(anonymous function) ember.js:4360
Ember.handleErrors ember.js:411
invoke ember.js:4358
tryable ember.js:4547
Ember.tryFinally ember.js:1102
Ember.run ember.js:4551
Ember.EventDispatcher.Ember.Object.extend._bubbleEvent ember.js:13924
(anonymous function) ember.js:13870
Ember.handleErrors ember.js:411
(anonymous function) ember.js:13861
jQuery.event.dispatch jquery.js:3075
elemData.handle jquery.js:2751

**Comment by heartsentwined** [comment]
?? 
I could have sworn I tested it myself ...? Must be an oversight, let me re-do it.
Sorry for that!

**Comment by heartsentwined** [comment]
My apologies, I didn't test thoroughly. It is a js `typeof null == 'object'` error. :disappointed:

**Comment by heartsentwined** [comment]
Try `ember-auth-source = 3.0.4` now.
On another note, this time I tried testing all links that I can find on your example app, and I discovered that if I register a new user (`foo@example.com`), and then try to sign in with your seeded example user (`josep@casals.name`), I would still be logged in as `foo@example.com`. This happens whether I have explicitly signed out `foo@example.com` or not. After that, I went to the console and deleted `foo@example.com`, and `josep@casals.name` can again sign in as expected.
`auth_token`s are passing through all the time, so I think this problem should come from your app.

**Comment by joscas** [comment]
Many thanks it works now! Also thanks for spotting that problem in my application. I haven't been able to reproduce it after the update but I'll implement a test for that and try to catch it.

**Comment by joscas** [comment]
Just a quick note in case someone checks that thread: The singin/signout problem reported in my application ( https://github.com/joscas/base_app) is now fixed.

**Comment by heartsentwined** [comment]
Congratz :smile: - that someone would include me.
