### ISSUE TITLE
Auth.signOut() not including token with Poltergeist

### ISSUE THREAD

**Issue by joscas** [heartsentwined/ember-auth#31]
Well, perhaps this is a bit paranormal but I've noticed that my cucumber test suite doesn't perform sign outs if I pick the poltergeist driver. What I see is that a call is made to the API but no token is included.

On my test application (https://github.com/joscas/base_app) this can be reproduced as follows:

1- Un-comment the last two lines of the sign_out feature: https://github.com/joscas/base_app/blob/master/features/sign_out.feature

2- Run rake cucumber

The test will fail because Auth.signOut() won't work with poltergeist.

3- Comment-out the poltergeist related lines in env.rb:
# require 'capybara/poltergeist'
# Capybara.javascript_driver = :poltergeist

4- Run rake cucumber again and the test will pass with selenium.

Maybe this is not a high priority bug :-) but it is annoying not being able to do headless testing.

**Comment by heartsentwined** [comment]
I am neither a Cuke fan nor a poltegeist user, so I can't promise anything, but I'll give it a look.

**Comment by heartsentwined** [comment]
No luck after hacking at your app and ember-auth source. I have no idea what the difference between poltergeist and selenium is (I mean, yes, there is webkit vs firefox, but this high-level difference is not helping...), nor do I understand what you mean by "Auth.signOut() not including token". Any pointers?

**Comment by joscas** [comment]
To help testing, I remove all the feature files except for the sign out one. Then I can see this in my log/test.log when I test with poltergeist:

Started DELETE "/users/sign_out" for 127.0.0.1 at 2013-04-12 12:48:33 +0200
Processing by SessionsController#destroy as JSON
Completed 400 Bad Request in 1ms (Views: 0.3ms)

When I test with selenium then I can see this:

Started DELETE "/users/sign_out" for 127.0.0.1 at 2013-04-12 12:53:21 +0200
Processing by SessionsController#destroy as JSON
  Parameters: {"auth_token"=>"hyWdA32Gbqs4mNwsLSwe", "session"=>{"auth_token"=>"hyWdA32Gbqs4mNwsLSwe"}}

My sign out action in ApplicationController does just this:

  signOut: function() {
    Auth.signOut();
    var self=this;
    Auth.on('signOutSuccess', function() {
      self.transitionToRoute('home');
    });
  },

The difference between poltergeist and selenium is just the auth token. That is why I say that Auth.signOut() is not sending the auth token with poltergeist.

I don't think this is a very critical problem right now but perhaps is a symptom of a problem that could show on certain browsers.

**Comment by heartsentwined** [comment]
I dug a little deeper into Poltergeist, and found out that it uses `phantomjs` as its backend. The thing is, `jasminerice` + `guard-jasmine` is also using `phantomjs`, and `ember-auth` tests run on these do pass.

This should be an assumption of browser state somewhere in the code, but I have no idea where to start this debugging.

**Comment by valpackett** [comment]
I have the same issue, but with any DELETE requests, not just signing out. There's no auth_token in params when a DELETE request is made from Capybara :-(

**Comment by valpackett** [comment]
This is so weird. From the WebKit point of view, everything is exactly the same in Opera Next and PhantomJS. Both in the Network tab and in the debugger (breakpoint at [jquery.em#L30](https://github.com/heartsentwined/ember-auth/blob/master/lib/request/jquery.em#L30)). But from Opera Next, Rails gets the auth_token. From PhantomJS, Rails doesn't => 401.

![opera_vs_phantom](https://f.cloud.github.com/assets/208340/661834/a21f7ba2-d741-11e2-98d7-c2d89c8d8183.png)

**Comment by valpackett** [comment]
mitmproxy confirms the issue is on the PhantomJS side:
![safari_vs_phantom_mitmproxy](https://f.cloud.github.com/assets/208340/661885/046f7d00-d744-11e2-9897-aa831005c43f.png)

**Comment by valpackett** [comment]
Okay, [the issue exists in PhantomJS tracker](https://github.com/ariya/phantomjs/issues/10873). This can be closed.

I think using a header is a possible fix for ember-auth users.

**Comment by heartsentwined** [comment]
Acknowledged.
