### ISSUE TITLE
Remove ember-rails dependency

### ISSUE THREAD

**Issue by stas** [heartsentwined/ember-auth#32]
Use `ember-source`, `ember-data-source` and `handlebars-source` as dependencies. Consider `ember-rails` as development dependency eventually.

**Comment by heartsentwined** [comment]
Good catch. I will use those source deps once I figure out which versions are compatible with `ember-auth`.

**Comment by heartsentwined** [comment]
I opted for `ember-source` only, and let ember itself figure out which versions of the others should work together.

**Comment by stas** [comment]
Awesome! :+1: 
Thank you.

**Comment by heartsentwined** [comment]
:smile:
