### ISSUE TITLE
auth_token not being sent

### ISSUE THREAD

**Issue by brandonparsons** [heartsentwined/ember-auth#34]
Hi there!

This seems like a cool project - I'm trying it out.

Not quite sure what I'm doing wrong, but the `auth_token` is not being sent along with requests.  Everything else appears to be working 100% correct (I've been following the tutorial).

For example, I can detect if signed in/out in views:

```
{{#if Auth.authToken}}
```

works fine.

But when I post to the backend for routes that require authentication, `auth_token` is not showing up in the params.

I can paste in whatever is required. Appreciate the help!

**Comment by heartsentwined** [comment]
I had just finished trying out the tutorial myself, and it was working. As a start, could you post your `Auth.Config` settings? - i.e. the object that you passed to `Auth.Config.reopen()`.

I'd start the debug by checking that all identifiers are specified and spelt correctly, e.g. `auth_token` vs `authentication_token`? (This has caught me in the past.)

If you don't mind, you can also make a repo and upload your tutorial app, and I'll take a look.

**Comment by brandonparsons** [comment]
Hey!  Thanks for the reply.

Here's the auth config:

```
Auth.Config.reopen
  tokenCreateUrl: '/session'
  tokenDestroyUrl: '/session'
  tokenKey: 'auth_token'
  idKey: 'user_id'
  userModel: Chat.User
```

The `userModel` part I added as a test, didn't seem to make a difference. 

I'm not quite sure if a spelling error would do it, as I can successfully log in via the `sign-in.coffee` and `sign-out.coffee` views, so I think its more of something I've misconfigured in your tool.

I'm also brand new to ember, so having doubly hard time debugging!

You can find the repo here:

https://github.com/brandonparsons/ember-auth-test.git

**Comment by heartsentwined** [comment]
You are using `ember-data`'s `DS.RESTAdapter`, instead of `ember-auth`'s `Auth.RESTAdapter`.

`store.js.coffee`:

``` coffee
Chat.Store = DS.Store.extend
  revision: 11
  adapter: DS.RESTAdapter.create({ # <-- here
    bulkCommit: false,
    url: '/api'
  })
```

Reference: relevant paragraph from the tutorial, on the [Model UI page](https://github.com/heartsentwined/ember-auth-rails-demo/wiki/Model-UI):

> ## Store and adapter
> 
> We will use `Auth.RESTAdapter` - it provides additional `ember-auth`-related functionalities while itself being an extension of `DS.RestAdapter`. We will also need to set the `url` setting, since we namespaced all resource API end points inside `/api`.
> 
> `store.coffee`:
> 
> ``` coffeescript
> EmberAuthRailsDemo.Store = DS.Store.extend
>   revision: 11
>   adapter: Auth.RESTAdapter.create
>     url: '/api'
> ```

**Comment by brandonparsons** [comment]
I figured it would be a simple misconfiguration!! Thanks for taking a look!!

**Comment by heartsentwined** [comment]
Glad it solved your problem. :smile:
