### ISSUE TITLE
Auth.jqxhr in new version

### ISSUE THREAD

**Issue by kevinansfield** [heartsentwined/ember-auth#46]
Thank you so much for version 5, it seems to have really cleaned things up!

One thing I have noticed is that under the sign in / sign out events section of http://ember-auth.herokuapp.com/docs it doesn't mention how to access the `jqxhr` object that was previously available at `Auth.jqxhr`

From the source I can see it's available at `App.Auth.get('jqxhr')` but I imagine it will help out new users to have that mentioned in the docs.

**Comment by heartsentwined** [comment]
It is in the section "Custom response data", which is one of the advanced use cases that are folded by default. I imagine if anybody wants to access `jqxhr`, one would be planning to do something with custom response. Or is it not obvious? I am open to your opinion - I am not a user of `jqxhr`

**Comment by kevinansfield** [comment]
OK, sorry, I had completely missed that section!
