### ISSUE TITLE
"Watching undefined global" warnings in latest version

### ISSUE THREAD

**Issue by kevinansfield** [heartsentwined/ember-auth#47]
After upgrading to v5 I'm seeing quite a few of these warnings in the console:

`WARNING: Watching an undefined global, Ember expects watched globals to be setup by the time the run loop is flushed, check for typos`

Is that something you have seen while working with ember-auth or do you think this is more likely my own code?

**Comment by heartsentwined** [comment]
I have not seen this warning when testing it. But if you have changed nothing except ember-auth, then it should be ember-auth's issue. Could you post your code so that I can try to reproduce it?

**Comment by kevinansfield** [comment]
I just noticed `ember-source` has been bumped from `rc3.2`->`rc3.3`. I'll roll that back to rule out any changes there and report back.

**Comment by kevinansfield** [comment]
The issue turned out to be a couple of forgotten `Auth.currentUser` calls in some handlebars partials. Oops!

**Comment by heartsentwined** [comment]
Thanks for the issue though, it shows me that I cannot leave out the Upgrade Guide just because it is too dramatic, otherwise someone will miss out something when upgrading, and run into errors. :disappointed:

**Comment by heartsentwined** [comment]
@kevinansfield @joscas an upgrade guide for the new version is out, at the [changelog](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide), just in case you want to reference it or use it as a checklist.

**Comment by joscas** [comment]
Thanks, that is very useful.
