### ISSUE TITLE
Auth.signin SyntaxError

### ISSUE THREAD

**Issue by joscas** [heartsentwined/ember-auth#50]
When I attempt to use `Auth.signin` with only `auth_token` and `remember` it doesn't work. If I attempt to do the same from the console I get a `SyntaxError`. It is strange because a dummy token works but a real one doesn't. See below the console output: 

Dummy token:

``` javascript
BaseApp.Auth.signIn({data: {'auth_token': 'notatoken','remember': true}});
```

```
Object {readyState: 1, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}
POST https://starter-app-staging.herokuapp.com/users/sign_in 401 (Unauthorized) jquery.js:8527
XHR finished loading: "https://starter-app-staging.herokuapp.com/users/sign_in". jquery.js:8527
```

Real token:

``` javascript
BaseApp.Auth.signIn({data: {'auth_token': 'SkydDzaQ2yby1cBh4Bq8','remember': true}});
```

```
Object {readyState: 1, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}
Uncaught SyntaxError: Unexpected end of input ember-auth.js:246
    Ember.Object.extend.canonicalize ember-auth.js:246
    Ember.Object.extend.canonicalize ember-auth.js:220
    $.ajax.done.fail.always.this$2 ember-auth.js:187
    fire jquery.js:1038
    self.fireWith jquery.js:1149
    done jquery.js:8077
    callback
```

**Comment by heartsentwined** [comment]
`ember-auth.js:246` reads

``` javascript
      return JSON.parse(input);
```

So that would most likely be an invalid JSON response error.

**Comment by heartsentwined** [comment]
My guess is that your server returns JSON on successful sign in, but just a plain-text error message on error. Your output shows

```
POST https://starter-app-staging.herokuapp.com/users/sign_in 401 (Unauthorized) jquery.js:8527
```

which is an error.

**Comment by joscas** [comment]
Yes, the first request is unauthorized because it uses a dummy token but the second one doesn't even reach the server because it generates a SyntaxError.

This gives syntax error in the console:

``` javascript
BaseApp.Auth.signIn({data: {'auth_token': 'SkydDzaQ2yby1cBh4Bq8','remember': true}});
```

So this is invalid JSON: `{data: {'auth_token': 'SkydDzaQ2yby1cBh4Bq8','remember': true}}`

```
JSON.parse({data: {'auth_token': 'SkydDzaQ2yby1cBh4Bq8','remember': true}}) -> SyntaxError: Unexpected token o
```

**Comment by heartsentwined** [comment]
This is valid JSON

```
{"data": {"auth_token": "SkydDzaQ2yby1cBh4Bq8","remember": true}}
```

Strings in double quotes, both in keys and values.

[This JSON validator](http://jsonformatter.curiousconcept.com/) may help.

**Comment by joscas** [comment]
Still provoking an error in the console:

```
JSON.parse({"data": {"auth_token": "SkydDzaQ2yby1cBh4Bq8","remember": true}})
SyntaxError: Unexpected token o
```

**Comment by heartsentwined** [comment]
Dear me, we are venturing away from `ember-auth` into pure js syntax issues.

This is valid js object:

``` javascript
BaseApp.Auth.signIn({data: {auth_token: 'SkydDzaQ2yby1cBh4Bq8', remember: true}});
```

(_No_ quotes around keys.)

You can't pass JSONs around in js, you pass objects around.

JSON.parse expects a JSON _string_, so you do 

``` javascript
JSON.parse('{"data": {"auth_token": "SkydDzaQ2yby1cBh4Bq8","remember": true}}');
```

**Comment by heartsentwined** [comment]
MDN references:
- [object](https://developer.mozilla.org/en-US/docs/JavaScript/Guide/Working_with_Objects)
- [json](https://developer.mozilla.org/en-US/docs/JSON)

**Comment by joscas** [comment]
So sorry, the fact that my test with a dummy token worked (by pure chance I guess) made me think the problem was with the token itself. Many thanks for your help.
