### ISSUE TITLE
Docs: Ember.Auth.create must be called before instantiating store

### ISSUE THREAD

**Issue by kevinansfield** [heartsentwined/ember-auth#51]
I just ran into an issue where the `auth_token` wasn't being added to the `params` data.

The solution was to swap the order these two lines in `application.js` from:

```
//= require ./app/store
//= require ./app/auth
```

to 

```
//= require ./app/auth
//= require ./app/store
```

Where `./app/auth` is the file that contains the ember-auth setup.

Perhaps it would be good to mention in the docs that `Ember.Auth.create` setup must happen before `DS.Store.extend`?

**Comment by heartsentwined** [comment]
It's already there in the first section of the [docs](http://ember-auth.herokuapp.com/docs).
