### ISSUE TITLE
Summary and temporary hack for improper order of redirect() and model() calls by ember.

### ISSUE THREAD

**Issue by ralfschimmel** [heartsentwined/ember-auth#52]
Not so much an issue, more a summary with temporary solution:

After reading:

 emberjs/ember.js#2041
 emberjs/ember.js#1786
 #29 
 https://gist.github.com/stefanpenner/9ccb0503e451a9792ed0

I came up with the following solution for a route which is working with the current ember.js, ember-data and ember-auth, in combination with the 'remember' module, when loading a 'deeplink' with models that require authentication to load.

So to get direct access to a route with a dynamic segment, the following seems to work for now, remember that this is a hack and ember or ember-data fixes as mentioned above hopefully make this redundant soon:

```
Blaat.SecretRoute = Ember.Route.extend(Blaat.Auth.AuthRedirectable);
Blaat.PaperRoute = Blaat.SecretRoute.extend({

    id: null,

    model: function(params) {
        this._super();
        if (Blaat.Auth.get('signedIn')) {
            return Blaat.Paper.find(params.paper_id);
        } else {
            this.set('id', params.paper_id);
            return null;
        }
    },

    setupController: function(controller, model) {
        if (!model) {
            if (Blaat.Auth.get('signedIn')) {
                controller.set('content', Blaat.Paper.find(this.get('id')));
            } else {
                var self = this;
                Blaat.Auth.on('signInSuccess', function() {
                    controller.set('content', Blaat.Paper.find(self.get('id')));
                });
            };
        }
    }
});
```

**Comment by joscas** [comment]
+1 This hack is the only way I know that would allow reloading routes that require authorization so far. I've tried using observers to set the content once Auth is completed but couldn't make this kind of strategy work. Maybe someone could post a working example with observers?. I hope there will be an easier way to do that in the near future once Ember.js and Ember data become more mature.

**Comment by heartsentwined** [comment]
A very annoying issue for now, but indeed I'm working on a demo todo app that includes CRUD operations on models, auth-only or not. I cannot make a fully transparent API that would not require any change to client-side code, but here is what I have so far: https://gist.github.com/heartsentwined/5584732

It's the best I can come up with so far, but it still requires userland code to include an `AuthableRoute` mixin, and to swap out `model()` declarations for an `authModel()` one (and let the mixin use the `model()` hook).

**Caution!** This is a work-in-progress. It seems to work so far, but even I myself have not finished the work. I'm just posting it just in case it inspire anybody to better ideas.

**Comment by ralfschimmel** [comment]
Seems like a viable option, preventing duplicate code.
I'll give it a shot tonight to see if it works!

**Comment by heartsentwined** [comment]
@ralfschimmel let me reiterate that it is a **work-in-progress** :no_mouth:

**Comment by darthdeus** [comment]
I'm having the same problem with the observers, it doesn't seem to work properly.

This also brings me to a little offtopic, how do you guys solve having a different layout for user with/without session?

**Comment by heartsentwined** [comment]
@darthdeus I'll post the full solution once I get it done.

As for your "offtopic", are you looking for simply this?

```
{{#if App.Auth.signedIn}}
  You are signed in!
{{else}}
  Please sign in first!
{{/if}}
```

**Comment by darthdeus** [comment]
@heartsentwined Unfortunately no, what I meant is different layout with outlets, for example

``` html
{{#if App.Auth.signedIn}}
  <div class="authenticated">
    Hi {{App.Auth.user.username}}
    {{outlet}}
  </div>
{{else}}
  {{outlet}}
{{/if}}
```

This is oversimplified, but the general problem is that I need a different layout wrapping the main outlet, because the login screen has a completely different design.

**Comment by heartsentwined** [comment]
@darthdeus Ember has a dedicated functionality for [adding layout to views](http://emberjs.com/guides/views/adding-layouts-to-views/). I haven't tried but I _guess_ you can make `layoutName` a computed property observing on `App.Auth.signedIn`.

**Comment by heartsentwined** [comment]
Failing that (i.e. ember doesn't automatically `rerender()` the view), then I think it would be more complicated if you want to do it in one template. Again I venture to _guess_ that you can't just move the `outlet` away, because `ember` relies on

``` html
<script id="metamorph-1-start" type="text/x-placeholder"></script>
<script id="metamorph-1-end" type="text/x-placeholder"></script>
```

tags, particularly the "id" part, to update the hooks. I haven't dug deep into `ember`'s code yet, but it depends on whether `ember` can `rerender()` the whole view for these `{{#if}}` helpers.

Still failing that, you would have to either do some manual patching (and probably use the `render()` or `rerender()` methods), or I might suggest that you break up your views into logical but separable sections (e.g. `wrapper` -> `header` & `footer`).

**Comment by heartsentwined** [comment]
Update: ember has got a new router, which is heavily relevant to authenticated-backed apps. I'm working with it to update ember-auth with the new APIs. For now, this issue is put on hold - I'll reproduce the scenario after I finish with the new router, and see if the issue persists.

Ref:
- [gist](https://gist.github.com/machty/5723945)
- [presentation](https://machty.s3.amazonaws.com/ember-facelift-presentation/index.html)

**Comment by ralfschimmel** [comment]
The new router should absolutely fix our issues, they did an awesome job on that.
Looking forward to your new implementation, and good luck!

**Comment by heartsentwined** [comment]
New router solves all our problems here. We don't have to touch `redirect()` or `model()`. The `model()` hook can use the standard ember API in userland code. However, it does rely on redirection, as

> the new router now _encourages_ you to use `authRedirectable` as "the ember way" of solving auth-only routes (with auth-only models)

---

`7.x` branch now released, with rc6 (new router!) support. [changelog](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md), [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide), [docs](http://ember-auth.herokuapp.com/docs) and [demo](https://github.com/heartsentwined/ember-auth-rails-demo/) all properly updated. Main notes:
- `ember-auth` now _requires_ ember `rc6` or above
- the new router now _encourages_ you to use `authRedirectable` as "the ember way" of solving auth-only routes (with auth-only models)
- thus you might want to pair it with `actionRedirectable` too for user experience
- despite this being a major version update, it would likely not break most userland code; the BC breaks are not in main, documented API
