### ISSUE TITLE
Cross domain, async calls no longer working with FireFox

### ISSUE THREAD

**Issue by mjallday** [heartsentwined/ember-auth#55]
I noticed that when firing ajax calls ember-auth is [setting](https://github.com/heartsentwined/ember-auth/blob/28ac6bccd6847c2b0b0898c36add98b2b69213da/lib/module/url-authenticatable.em#L47) `async: false` and this, in combination with my apps `withCredentials: true` flag, is causing [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=701787) to no longer work.

My initial reaction was to remove the `async: false` from ember-auth since it appears to be a setting that causes the browser to freeze while it waits for response. However, I wanted to check what the reasoning behind this was in case this is not the correct way to work around this issue.

Can someone tell me what's going on?

**Comment by heartsentwined** [comment]
The same reason behind both places (auto-recall in `rememberable` and auto-authenticate in `urlAuthenticatable`): to prevent `ember` from executing code meant for non-authenticated users, in case we have a valid user session. Issuing a blocking API call would ensure that user session is properly setup before `ember` does its own bootstrapping.

Simple use case: you have setup your app to redirect non-authenticated users to a `sign-in` route, but you use auto-authenticate in `urlAuthenticatable` too. A user visits your app in a URL with credentials (e.g. `http://example.com/dashboard?auth[user]=foo&auth[pass]=bar`) Now when the app is setup, an API call will be sent to the server. If this API is left async, then `ember` will see a non-authenticated user session, and promptly redirect your user to the `sign-in` route. Sometime afterwards, the server sends back a signed in session, but it's already "too late", `ember` has already finished bootstrapping.

**Comment by heartsentwined** [comment]
@mjallday what is the status of this issue? do you still need anything fixed on the `ember-auth` side?

**Comment by mjallday** [comment]
I'm not 100% sure to be honest!

We can change the way we pass with creds around to work around the way ember auth works but is that what's best for your product?

If no one else is running into this issue then I guess we are the outliers and should conform so you can close it until more people run into the same issue unless you can think of a better way to achieve the blocking requests.

**Comment by heartsentwined** [comment]
Well I had wanted to find a better way to when developing these features, but I dugged into `ember` and i couldn't find any such API. If `ember` releases an official API for "pausing" and "resuming" the app initialization, then we would gladly adopt it. The closest to it now is `deferReadiness()` and `advanceReadiness()`, but it is restricted to a one-off usage, i.e. we cannot pause, resume, pause, and resume again. I have seen multiple use cases where people do use this method in production for their own logic, so it's a bad idea to hijack it in `ember-auth` (hence preventing userland usage).

As you suggested, closing for now unless issue resurfaces in more use cases.

**Comment by heartsentwined** [comment]
@mjallday ember has released a new version (`rc6`), and ember-auth has upgraded with it (`7.x`). This new version removed the need for `{ async: false }` in both modules, so you can safely use it with firefox now.

**Comment by mjallday** [comment]
Awesome. That comes about a week too late after we refactored to work around the issue :)

I appreciate the update however and will take a look and see if it helps to simplify our code base.
