### ISSUE TITLE
GPL 3.0

### ISSUE THREAD

**Issue by inscore** [heartsentwined/ember-auth#57]
I think the GPL 3.0 licence might prevent me and others from using ember-auth... "The GNU General Public License does not permit incorporating your program into proprietary programs."

Please consider a more permissive licence, such as MIT, for ember-auth and ember-auth-rails so that I and others can use ember-auth in projects where we don't intend to release the full application source.

**Comment by hamstarr** [comment]
+1
+1 for the ember-auth-rails gem too.

**Comment by heartsentwined** [comment]
@inscore @hamstarr `ember-auth` is now licensed under MIT. I would have wanted to dual-license it, but `package.json` doesn't support multiple licenses :disappointed: (`gemspec` does, though, but better keep it uniform)

**Comment by hamstarr** [comment]
Excellent!  Thanks.

On 29 May 2013 10:31, heartsentwined notifications@github.com wrote:

> @inscore https://github.com/inscore @hamstarrhttps://github.com/hamstarr
> ember-auth is now licensed under MIT. I would have wanted to dual-license
> it, but package.json doesn't support multiple licenses [image:
> :disappointed:](gemspec does, though, but better keep it uniform)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/heartsentwined/ember-auth/issues/57#issuecomment-18605383
> .

## 

Simon Hamilton
RUMBLE LABS
rumblelabs.com
+442895680011
@hamstarr

**Comment by inscore** [comment]
Thanks!
