### ISSUE TITLE
Signin Call to users/:id?

### ISSUE THREAD

**Issue by asia653** [heartsentwined/ember-auth#58]
Why is there a call to GET http://localhost:3000/users/1 404 (Not Found) after signin if the json returned by that url is not stored anywhere? The user id seems to be available regardless of whether that restful route is responding or not

**Comment by darthdeus** [comment]
Isn't this just to verify the token?

**Comment by heartsentwined** [comment]
@Edwardzyc can you give me an example of your setup? This might or might not be a bug depending on your demonstrated use case. A sample of your json response (`404` or successful) would also be helpful.

**Comment by asia653** [comment]
I've noticed App.Auth.get('user') fails unless the call to the users/:id passes so I assume that it is grabbing user object.

Anyways, looks like it is intended behaviour because it is going to the show action of the user controller. The 404 is actually the rails error message "The action 'show' could not be found for UsersController"
