### ISSUE TITLE
STI models

### ISSUE THREAD

**Issue by martinstannard** [heartsentwined/ember-auth#59]
I'm using a rails backend with an STI Users class to implement mulitple roles within my app. I'd like to be able to signin as an Admin, Educator or Parent and receive back the relevent ember model. I've implemented signin as described in the docs, but can't work out how to have ember-auth use the correct model depending on the type of user I'm trying to authenticate.

For instance, if I signin as an Educator I'm getting an model of type Educator returned whereas ember-auth expects a User model. I've considered adding the type field to the data returned by App.Auth so I then know which sort of user has been signed in and can instantiate the appropriate model. Is this the correct way to handle this situation?

**Comment by heartsentwined** [comment]
Consider using the added polymorphism introduced in emberjs/data#750, and give `ember-auth` a unified `User` / `Member` / whatever model. I wouldn't want to add a fresh layer of polymorphism support to `ember-auth` when this functionality is already out there.

**Comment by martinstannard** [comment]
Thanks, I'll look into that as a solution.
