### ISSUE TITLE
resolveUrl problem

### ISSUE THREAD

**Issue by joscas** [heartsentwined/ember-auth#6]
I've tried to replicate the example and I get this error in function resolveUrl:

Uncaught TypeError: Cannot read property '0' of null ember-auth.js:67
window.Auth.evented.create.resolveUrl ember-auth.js:67
window.Auth.evented.create.signIn ember-auth.js:17
BaseApp.SignInController.Ember.ObjectController.extend.signIn sign_in_controller.js:5
Ember.ControllerMixin.Ember.Mixin.create.send ember.js:12078
(anonymous function) ember.js:26190
(anonymous function) ember.js:4075
Ember.handleErrors ember.js:410
invoke ember.js:4073
tryable ember.js:4263
Ember.tryFinally ember.js:1048
Ember.run ember.js:4267
ActionHelper.registeredActions.(anonymous function).handler ember.js:26188
(anonymous function) ember.js:13421
Ember.handleErrors ember.js:410
(anonymous function) ember.js:13413
jQuery.event.dispatch jquery.js:3075
elemData.handle jquery.js:2752

I know this is not enough information by far and I apologize for that. But can you give me an idea of what could be the problem or where to start debugging?

**Comment by heartsentwined** [comment]
I would be glad to help you, but I need more info to replicate your issue. First, where are you now replicating the example? There are at least two branches (widget-style templates vs full-page-style templates) and a couple of optional features (redirection, events, remember me). Also post your `Auth.Config` settings (the object that you pass to `Auth.Config.reopen()`) and, if you don't mind, your code up to now. I don't mind if it's just the output JS instead of original coffeescript, as long as it is not minified.

**Comment by joscas** [comment]
Many thanks for your help. I have failed with both branches with the same error. Haven't gone further than login. 
Please see here: https://github.com/joscas/base_app

Here's my Auth.config:

Auth.Config.reopen({
  tokenCreateUrl: '/users/sign_in',
  tokenDestroyUrl: '/users/sign_out',
  tokenKey: 'auth_token',
  idKey: 'user_id',
  rememberMe: true,
  rememberTokenKey: 'remember_token',
  rememberPeriod: 7
});

**Comment by DCKT** [comment]
Hi, I've got the same problem. In my case I use the Widget Style, here is my Auth.config : 

```
Auth.Config.reopen
  tokenCreateUrl: '/login'
  tokenDestroyUrl: '/logout'
  tokenKey: 'auth_token'
  idKey: 'user_id'
  rememberMe: true
  rememberTokenKey: 'remember_token'
  rememberPeriod: 7
```

The problem must came from the URL, but I checked everything and all looks right. 
Hope you'll find an issue.

**Comment by heartsentwined** [comment]
quick update, @DCKT and @joscas, just to note that I am working on the issue, I'll let you know once I have isolated the problem and have found a solution.

**Comment by heartsentwined** [comment]
Issue should be resolved in latest bugfix (it is a missing guard clause). @joscas I cloned your repo, ran `bundle update`, and it is working for me.

Closing issue unless problem resurfaces.

**Comment by joscas** [comment]
Many thanks, that fixes the 'Uncaught TypeError' error. However, I'm getting the request against the root path instead of against '/users/sign_in' as specified in my Auth.config.
Is this still a bug or is it my config that is wrong?

See my rails log:

Started POST "/" for 127.0.0.1 at 2013-03-11 19:09:59 +0100
Processing by ApplicationController#index as JSON
  Parameters: {"email"=>"joe@example.com", "password"=>"[FILTERED]", "application"=>{"email"=>"joe@example.com", "password"=>"[FILTERED]"}}

**Comment by heartsentwined** [comment]
should be a bug, I'll look into it

**Comment by heartsentwined** [comment]
@joscas it seems to be a sprockets (rails asset pipeline) issue: your `auth.js` was not included at all (despite the `require_tree .` directive). I included `auth.js` with an explicit directive in `application.js`, and your `Auth.Config` is now read correctly.

``` js
//...
//= require base_app
//= require auth
BaseApp = Ember.Application.create();
//= require_tree .
```

Let me know if you encounter any further issues.

**Comment by joscas** [comment]
Does work. Thanks!

**Comment by heartsentwined** [comment]
You're welcome @joscas.
