### ISSUE TITLE
'FormData' is undefined

### ISSUE THREAD

**Issue by ralfschimmel** [heartsentwined/ember-auth#60]
In IE9 normal mode i'm getting this error:

'FormData' is undefined

It seems that it tries to use FormData which is not supported in IE9, is there any way to tell ember-auth not to use FormData? I did see some references on this but cannot find how to do this in the docs.

Using ember rc.3 and jquery 1.9.1.

Config:

```
App.Auth = Ember.Auth.extend({
    signInEndPoint: '/login',
    signOutEndPoint: '/logout',
    baseUrl: function() {
        return App.getHost();
    }.property(),
    userModel: 'App.User',
    tokenKey: 'token',
    tokenIdKey: 'user_id',
    modules: ['emberData', 'rememberable', 'authRedirectable', 'actionRedirectable'],
    rememberable: {
        tokenKey: 'token',
        period: 14,
        autoRecall: true
    },
    authRedirectable: {
        route: 'index'
    },
    actionRedirectable: {
        signOutRoute: 'index'
    }
}).create();
```

**Comment by heartsentwined** [comment]
@ralfschimmel _should_ be fixed on `6.0.5` (a very simple fix _in theory_, because it's just an undefined variable), but I don't have an IE at hand right now to absolutely verify.
