### ISSUE TITLE
Auth Token not being sent (new version)

### ISSUE THREAD

**Issue by brandonparsons** [heartsentwined/ember-auth#65]
Hi there,

Sorry to open up a very similar issue (see https://github.com/heartsentwined/ember-auth/issues/34).

I've upgraded to the new version of ember-auth, and I've tried to copy your demo exactly.  Ember auth is properly signing in (the AuthView changes, etc.), but it is not sending the auth_token along with all requests after signin.

My problem last time was that I was not using the Auth.RESTAdapter, but that seems to have been changed now in the new version.

_auth.coffee_

(I believe the tokenLocation: 'param' option is default)

```
App.Auth = Em.Auth.create
  signInEndPoint: '/users/sign_in'
  signOutEndPoint: '/users/sign_out'

  tokenKey: 'auth_token'
  tokenIdKey: 'user_id'
```

_store.coffee_

```
App.Store = DS.Store.extend
  adapter: DS.RESTAdapter.create
    url: '/api/v1'
```

_users controllers_

(All generated by ember)

_users routes_

```
App.UsersRoute = Em.Route.extend
  model: ->
    if App.Auth.get('signedIn')
      App.User.find()
```

```
App.UsersIndexRoute = Ember.Route.extend
  model: ->
    if App.Auth.get('signedIn')
      App.User.find()
```

Any help you could provide would be appreciated. I can't for the life of me figure out why it is not sending the `auth_token`.  The whole sign-in process is working perfectly.  Thanks!!!

**Comment by brandonparsons** [comment]
Think I might have sorted it out.  Need to require the `auth.coffee` file prior to the `store.coffee` file. I will reopen later if it is still blowing up on me.

**Comment by mattgoldman** [comment]
@brandonparsons Hmmm, I'm having the same exact problem, and I'm including the auth before the store. Did you discover any other cause?

``` javascript
App.Auth = Ember.Auth.create({
  signInEndPoint: '/users/sign_in',
  signOutEndPoint: '/users/sign_out',
  tokenKey: 'auth_token',
  tokenIdKey: 'user_id'
});

App.Store = DS.Store.extend({
  revision: 12,
  adapter: DS.RESTAdapter.create({
    url: '/api/v1'
  })
});
```
