### ISSUE TITLE
Take advantage of new router features

### ISSUE THREAD

**Issue by bakura10** [heartsentwined/ember-auth#66]
Hi,

I'm not an EmberJS expert (especially about its internals), but it seems that the new router rewrite introduced in RC6 contains some interesting stuff for you that could reduce your code (https://machty.s3.amazonaws.com/ember-facelift-presentation/index.html#/3)

Thanks !

**Comment by heartsentwined** [comment]
already working on it

**Comment by dustMason** [comment]
+1!

**Comment by heartsentwined** [comment]
`7.x` branch now released, with rc6 (new router!) support. [changelog](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md), [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide), [docs](http://ember-auth.herokuapp.com/docs) and [demo](https://github.com/heartsentwined/ember-auth-rails-demo/) all properly updated. Main notes:
- `ember-auth` now _requires_ ember `rc6` or above
- the new router now _encourages_ you to use `authRedirectable` as "the ember way" of solving auth-only routes (with auth-only models)
- thus you might want to pair it with `actionRedirectable` too for user experience
- despite this being a major version update, it would likely not break most userland code; the BC breaks are not in main, documented API
