### ISSUE TITLE
Is it possible to set a token to be used?

### ISSUE THREAD

**Issue by bugant** [heartsentwined/ember-auth#67]
Is it possible to set the value of the authToken to be used via code?

I've tried App.Auth.set('authToken', 'foo') but it is not added to request headers in subsequent requests.

I need this since I have a never expiring token and if I try to use rememberable it expects to get an url where to retrive a new token given the old one.

**Comment by heartsentwined** [comment]
This feature has been added to master.

If you want to sign in a user, whose authentication information is represented by the (normally expected) server response `{ foo: 'bar' }`, then you do:

``` javascript
App.Auth.createSession({ foo: 'bar' });
```

And to sign out this user:

``` javascript
App.Auth.destroySession();
```

Basically what this does is to simulate / mock a server response, and perform all the housekeeping work for sign in / sign out. All without hitting the server.

Your use case will probably be something like

``` javascript
App.Auth.createSession({ auth_token: 'foo' });
```

I'm working on several other features, and I will make a new release when I'm done.
