### ISSUE TITLE
Doesn't work with rc6

### ISSUE THREAD

**Issue by valpackett** [heartsentwined/ember-auth#68]
```
TypeError: 'undefined' is not a function (evaluating 'get$(get$(this, 'router'), 'location').setURL(result)')
```

(ActionRedirectable.redirect)

Everything works fine when I change Ember rc6 back to rc5

**Comment by heartsentwined** [comment]
No, it doesn't work with rc6 yet - I'm writing the upgrade now

**Comment by heartsentwined** [comment]
`7.x` branch now released, with rc6 (new router!) support. [changelog](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md), [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide), [docs](http://ember-auth.herokuapp.com/docs) and [demo](https://github.com/heartsentwined/ember-auth-rails-demo/) all properly updated. Main notes:
- `ember-auth` now _requires_ ember `rc6` or above
- the new router now _encourages_ you to use `authRedirectable` as "the ember way" of solving auth-only routes (with auth-only models)
- thus you might want to pair it with `actionRedirectable` too for user experience
- despite this being a major version update, it would likely not break most userland code; the BC breaks are not in main, documented API
