### ISSUE TITLE
Don't find the authToken

### ISSUE THREAD

**Issue by DCKT** [heartsentwined/ember-auth#7]
Hi,

Great job for your bugfix, now I can send the mail and password to the DB but I don't know why, when I check if the authToken is here (in the template), it doesn't work.

Here is my Auth.Config : 

``` Auth.Config.reopen
  tokenCreateUrl: '/api/login'
  tokenDestroyUrl: '/api/logout'
  tokenKey: 'auth_token'
  idKey: 'user_id'
  rememberMe: true
  rememberTokenKey: 'remember_token'
  rememberPeriod: 7
```

How can I see the content of the authToken ? 

Thank you very much.

**Comment by heartsentwined** [comment]
should be a bug, I'll look into it

**Comment by heartsentwined** [comment]
Is it possibly [this issue](https://github.com/heartsentwined/ember-auth/issues/6#issuecomment-14759088) ? (in short: an explicit `require` directive is needed for sprockets)

**Comment by heartsentwined** [comment]
@DCKT Would you mind posting your ember app code, so that I can try to replicate your issue?

**Comment by heartsentwined** [comment]
Thanks, but `application_view.js.coffee` has the code of `store.js.coffee` - copy-and-paste error? ;-)

There is also

``` js
//= require rails_ember
```

in your sprockets directives, what does `rails_ember.js` do?

**Comment by heartsentwined** [comment]
Thanks, I'll let you know of any updates

**Comment by DCKT** [comment]
I found the problem, it wasn't an ember-auth problem.. In my controller when I returned the JSON I use "token" and not "auth_token" as key ..

Thanks again !

**Comment by heartsentwined** [comment]
Oh, glad you found the solution anyway :-)
