### ISSUE TITLE
Proposal: only extend Ember.Auth, not create it

### ISSUE THREAD

**Issue by ayarulin** [heartsentwined/ember-auth#70]
I have some design proposals, that should make this awesome gem more handy, and it will better fit the Ember style :)
- App.Auth should be a class, not an instance,
- Auth Mixins should be a part of Auth namespace, not the 'auth' instance
- And finally 'auth' instance should be created in app initializer, and injected into container like 'auth:main'. (It also can be injected in all routes and controllers), no manual Auth.create();

So after that, app will looks like this:

``` javascript
App.Auth = Ember.Auth.extend({
// we just define our own a App.Auth class, not creating an instance.
  signInEndPoint: '/custom-sign-in'
})

App.Route = Em.Route.extend(App.Auth.AuthRedirectable, {
// no changes here, but the App.Auth is our class now, not instance
})

//use the container to get auth instance
var auth =  this.container.lookup("auth:main");

//actually, it is already injected into controllers and routes, so just:
App.Controller = Em.Controller.extend({
  whoAmIBinding: 'auth.user'
})



```

``` handlebars
{{#if auth.signedIn}}
 {{whoAmI}}
{{/if}}
```

In testing `App.reset()` now will reset Auth, since it recreates Auth instance within initializer.

Have any thoughts about this?

**Comment by heartsentwined** [comment]
Frankly, I am not familiar with this pattern enough to either comment on it or implement it. Just two quick thoughts:

First, the original intention is that `Ember.Auth` is a class, while `App.Auth` is the instance. The latter's purpose is to allow access from all parts of the app, so I chose to register a variable on the `App` namespace. It could have been a global variable `foo` for that matter, but the former seems to be more "the ember way".

Second, you mentioned that

``` javascript
var auth =  this.container.lookup("auth:main");
```

will become _the_ way of grabbing an auth instance. However, although this is found frequently in ember's code base, this appears nowhere in userland API. Usually ember has exposed other APIs for accessing instances (`controllerFor()` and friends). - Or I don't understand your final code example well

``` javascript
//actually, it is already injected into controllers and routes, so just:
App.Controller = Em.Controller.extend({
  whoAmIBinding: 'auth.user'
})
```

Do you mean, that if I register `foo:main`, then it will already be injected automatically everywhere, as `foo`?

Again, I admit that I am not familiar enough with this part of ember. I'll be glad for more pointers - or of course PRs welcome!

**Comment by ayarulin** [comment]
@heartsentwined, exactly, type injection allows us to access variable from any object of that type. Actually the only blocker of this approach is that for now we access to mixins from an current instance of Em.Auth. To be more clear I will make PR ASAP.

**Comment by tstirrat** [comment]
:+1: 

I agree with these suggestions, too.

To clarify on the injection stuff, you can read how to do it here: http://madhatted.com/2013/5/26/communication-between-controllers-in-ember-js

So, assuming you made the changes suggested above, injection could be done like so:

``` javascript
App = Em.Application.create();

App.Auth = Ember.Auth.extend({
  signInEndPoint: '/login'
})

App.initializer({
  name: "auth",
  initialize: function (container) {
    // instantiates a singleton at auth:main
    container.register('auth:main', App.Auth, {singleton: true});
    // inject auth:main as "auth" in all controllers
    container.typeInjection('controller', 'auth', 'auth:main');
    // ..same could be done with routes
  }
});

// now available in all controllers as "auth"
App.SomeUserController = Em.ObjectController.extend({
  isMe: function () {
    return this.get('content') === this.get('auth.user');
  }
});
```

And in the templates, you can access it like so:

``` handlebars
{{#if auth.signedIn}}
  Hello {{auth.user.fullName}}
{{/if}}
```

Which would then allow any controller to access the auth simply by `this.get('auth')`

**Comment by sarjanen** [comment]
@AdRulz how's it going with your PR? Seems like this is the only way to getting Ember Auth to work with Ember Data 1.0.0

**Comment by heartsentwined** [comment]
Hooray!

Injection pattern implemented in `9.x`. The usual code-generating [docs](http://ember-auth.herokuapp.com/) and [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide) to help with the transition.

Please reopen this ticket if something is wrong with the new injection pattern implementation.

**Comment by tstirrat** [comment]
awesome :)
