### ISSUE TITLE
does not redirect if authentication with ember-auth-rememberable fails (4xx status response)

### ISSUE THREAD

**Issue by joebartels** [heartsentwined/ember-auth#75]
The rememberable feature works as expected when my server validates the `ember-auth-rememberable` cookie sent by Ember-Auth (200 response + user_id  + new token) but if my server decides the token is invalid(expired, or just incorrect) then it returns a 403 status code and Ember-Auth does not redirect to the route designated in authRedirectable.

To test:
-call Auth.signIn with valid credentials and the server returns `200` status and:

```
user_id : johnDoe,
auth_token: abcdefg,
remember: 123456
```

-navigate to a route that has `App.Auth.AuthRedirectable` passed to it
-refresh the page and the token in the cookie is successfully authenticated by the server which returns `200` code along with `user_id`, `auth_token` and `remember`
-manually change the remember token on the server to something different
-refresh the page, the server can't validate the token from the cookie since now it's different from record on server
-Ember throws an `Error while loading Route` and `uncaught exception: <Ember.Deferred:ember334>` errors

Here is my configuration -it's pretty standard:

```
App.Auth = Ember.Auth.create({
  modules: ['emberData',
            'rememberable',
            'authRedirectable'
            ],
  signInEndPoint: 'api/1.0/sign_in',
  signOutEndPoint: 'api/1.0/sign_out',
  tokenKey: 'auth_token',
  tokenIdKey: 'user_id',
  userModel: 'App.User',

  rememberable: {
    tokenKey: 'remember',
    period: 7,
    autoRecall: true
  },
  authRedirectable: {
    route: 'sign_in'
  }
});
```

**Comment by joebartels** [comment]
If there exists an ember-auth-rememberable cookie (which is not correct) and a  `POST` is sent to the `sign_in` route, initiated by `rememberable`'s `recall` function (after a hard page reload for example). If the response is a 4xx status code (because of invalid token) I can get the expected behavior (of redirecting to `sign_in` route) if I make small modification to the `Rememberable` Ember Object.

All I did was switch `return reject()` with `return resolve()` ..So far I get results I expect but is there any reason why this is a bad fix? it feels slightly wrong to do it like this. I guess I'd be curious to know why `reject()` doesn't work as expected in this case?

``` javascript
recall: function (opts) {
  ...
  if (!get$(get$(this$, 'auth'), 'signedIn') && (token = this$.retrieveToken())) {
    ...
    return get$(this$, 'auth').signIn(opts).then(function () {
      return resolve();
    }, function () {
      return resolve()      // ask ember-auth to resolve it instead of reject()
    });
...
}));
```

**Comment by heartsentwined** [comment]
Digging into this, thanks for the issue report.

**Comment by heartsentwined** [comment]
Thanks for your big hint @joebartels , that's indeed the solution.

The reason behind is that, when adopting the promise pattern in ember's [new router](https://gist.github.com/machty/5723945), I had (wrongly) adopted its error handling in rejecting promises too. But `ember-auth` may need to execute code even after a sign in attempt failure state, just like the scenario you stated. Error handling is, instead, done by hooking onto the `signInError` event. Bad idea to mix these two error handling methods.

**Comment by joebartels** [comment]
thanks for looking at issue & explaining how the solution works. Looks like the error handling in the new router is very useful. We're all glad you're actively working on Ember-Auth to play nicely with the latest Ember releases! thanks!
