### ISSUE TITLE
Fail to load signIn route after url authentication

### ISSUE THREAD

**Issue by stimg** [heartsentwined/ember-auth#76]
ember 1.0 RC 6
ember-auth 6.0.5 (29 May 2013)
jQuery 1.9

```
    App.Auth = Ember.Auth.create({
        signInEndPoint: config.api.crossAuth,
        baseUrl: config.api.baseUrl + config.api.namespace,
        tokenKey: 'access_token',
        tokenIdKey: 'token_type',
        modules: ['emberData', 'urlAuthenticatable', 'authRedirectable', 'actionRedirectable'],
        urlAuthenticatable: {
            param: 'cross_token'
        },
        authRedirectable: {
            route: 'auth'
        },
        actionRedirectable: {
            signInRoute: 'login',
            signOutRoute: 'index'
        }
    });

    App.SecureRoute = Ember.Route.extend(App.Auth.AuthRedirectable, {
        activate: function () {
            this._super.apply(this, arguments);
            console.log('Secure route activated.');
        }
    });

    App.LoginRoute = App.SecureRoute.extend({
        activate: function () {
            this._super.apply(this, arguments);
            App.model.initDB().then(this.transitionTo('/'));
        }
    });
```

It works fine if I use App.Auth.signIn(), but if I try to use url parameter for authentication, no routes will be initialized and I get an error:

Error while loading route: TypeError {} ember.js:361
(anonymous function) ember.js:361
defaultErrorHandler ember.js:25470
trigger ember.js:24754
handleError ember.js:24988
invokeCallback ember.js:7096
(anonymous function) ember.js:7143
EventTarget.trigger ember.js:6927
(anonymous function) ember.js:7202
DeferredActionQueues.flush ember.js:4901
Backburner.end ember.js:4591
(anonymous function)

Uncaught TypeError: Cannot call method 'apply' of undefined ember-auth.js:614
Ember.Object.extend.redirect ember-auth.js:614
sendEvent ember.js:2096
notifyObservers ember.js:2431
Ember.propertyDidChange ember.js:2298
ChainNodePrototype.chainDidChange ember.js:3469
ChainNodePrototype.chainDidChange ember.js:3467
ChainNodePrototype.didChange ember.js:3504
chainsDidChange ember.js:2363
Ember.propertyDidChange ember.js:2297
iterDeps ember.js:2335
dependentKeysDidChange ember.js:2319
Ember.propertyDidChange ember.js:2296
ChainNodePrototype.chainDidChange ember.js:3469
ChainNodePrototype.chainDidChange ember.js:3467
ChainNodePrototype.didChange ember.js:3504
chainsDidChange ember.js:2363
Ember.propertyDidChange ember.js:2297
set ember.js:2518
Ember.Object.extend.start ember-auth.js:407
(anonymous function) ember-auth.js:389
sendEvent ember.js:2096
Ember.Evented.Ember.Mixin.create.trigger ember.js:11120
get$.extend.trigger ember-auth.js:14
superWrapper ember.js:1079
send.done.fail.this$1 ember-auth.js:164
fire jquery.js:1017
self.add jquery.js:1063
Ember.Object.extend.signIn ember-auth.js:163
Ember.Object.extend.signIn ember-auth.js:74
get$.reopen.signIn ember-auth.js:100
Ember.Object.extend.authenticate ember-auth.js:780
get$.reopen.redirect ember-auth.js:826
superWrapper ember.js:1079
Ember.Route.Ember.Object.extend.afterModel ember.js:25967
afterModel ember.js:25020
invokeCallback ember.js:7096
(anonymous function) ember.js:7139
EventTarget.trigger ember.js:6927
(anonymous function) ember.js:7194
DeferredActionQueues.flush ember.js:4901
Backburner.end ember.js:4591
(anonymous function) ember.js:4796

When I check line 614 of ember-auth:
614: return get$(get$(this, 'router'), 'transitionTo').apply(this, result);

get$(this, 'router') === null

If I enable signInSmart url auth works, but App.Auth.signIn doesn't redirect to '/', but stays on 'auth' route after successful auth.

Any help would be very appreciated.
Thanks.

**Comment by heartsentwined** [comment]
Could you try upgrading the `ember*` components? First there is a critical fix applied in `ember rc 6.2`, then also `ember-auth` has been rewritten for the new router at `ember-auth 7.x`.

Let me know if the issue persists in the latest versions.

**Comment by stimg** [comment]
Thank you! I've found workaround for it and it works for now. I'll make an update later and let you know if it works. BTW rc 7 is out today. Is ember-auth 7.x compatible with it?

**Comment by heartsentwined** [comment]
I've just released a new version (`ember-auth 7.1.1`), that has `ember rc 7` tested and all passed.

**Comment by stimg** [comment]
I've updated ember and ember-auth to latest versions. Routing works now correctly.

Thank you!

**Comment by heartsentwined** [comment]
Glad it helped.
