### ISSUE TITLE
Signin redirect 'issue' (module: actionRedirectable)

### ISSUE THREAD

**Issue by Globegitter** [heartsentwined/ember-auth#77]
We have an app we automatically set the remember_token, so whenever you refresh a page it obviously logs you in again (which I think, on another note, is a general problem with ember anyway, that when you refresh the page you loose the session. There is nothing you could really do with ember-auth, right?). This leads to an 'issue' when actionRedirectable is activated. 
Here is how I have it defined in case that helps anything:

``` javascript
    actionRedirectable: {
        signInSmart: true,
        signInRoute: 'index',
        signInBlacklist: ['signup', 'login'],
        signOutRoute: 'index'
    }
```

So when I go directly to any route without having the ember-app loaded or simply refresh a route with Cmd+R then I get redirected to the index-route (which in my case redirects me to another static route if logged in). 
If I remove the actionRedirectable I don't have that issue, but then obviously the automatic redirect after logging in doesn't work.
Shouldn't the signInSmart kick in here to redirect me to /#/user/? Or is there any other way this can be improved/fixed?

Edit: We are also using the default hash history API.

Btw, thank you for all your work, it is really appreciated.

**Comment by heartsentwined** [comment]
Try the fix in [this comment](https://github.com/heartsentwined/ember-auth/issues/69#issuecomment-20432137).

**Comment by Globegitter** [comment]
That works perfectly thanks. Though maybe it might be worth mentioning that in the docs because I can see that not everyone (such as me) really thinks about that at first.

**Comment by heartsentwined** [comment]
I'm still pondering about whether it's a docs problem or ember-auth's problem...

**Comment by Globegitter** [comment]
In my opinion, it would probably be slightly more elegant if in this case the order does not interfere with the 'smart' redirect. But I suppose it is also a question of how much work is it and is that worth it. However you decide, the most important thing is that it works ;)
