### ISSUE TITLE
A question about best practices.

### ISSUE THREAD

**Issue by kiwiupover** [heartsentwined/ember-auth#80]
G'day 

I'm giving a talk Wednesday Night July 17 about Ember-Auth at the Seattle Ember meetup.

I have one piece of code I'm not sure about. Is there a better way to lookup the login controller?

``` javascript
  App.Auth.on('signInError', function(){
    loginController = window.App.__container__.lookup('controller:login');
    loginController.setProperties({'loginError': true, 'isLoggingIn': false});
  });
```

Cheers
Dave

**Comment by heartsentwined** [comment]
Glad to hear about your talk!

It depends on where you're trying to access the controller. Usually there would be ember api methods for accessing them, where you're supposed to be able to access controllers.

Simple for routes: `this.controller` for the current corresponding controller; and `this.controllerFor('foo')` for other controllers.

For controllers, you first need to declare other controller dependencies via `needs`:

``` javascript
App.CommentsController = Ember.ArrayController.extend({
  needs: "post"
});
```

Then access them from the injected `controllers`:

``` javascript
// still inside App.CommentsController
postController = this.get('controllers.post');
```

This latter example is taken from the [official docs](http://emberjs.com/guides/controllers/dependencies-between-controllers/).

Cheers, and let me know if you need anything else. Too bad I'm not in Seattle.

**Comment by kiwiupover** [comment]
Thanks heaps for the reply. 

I should have been clearer. When I'm in the a callback like `App.Auth.on('signInError')` or one of the others, what is the best way to call a method on a controller. Say I want to show an error message to the user like this one.

``` handlebars
  {{#if loginError}}
    <div class="large-12 columns panel radius error_box">
      <span class="error"><i class="icon-warning-sign"></i> Invalid login.</span>
      <p>Incorrect username or password.</p>
    </div>
  {{/if}}
```

To show the error and I want set loginError to true. Is this the best way or is the

``` javascript
  App.Auth.on('signInError', function(){
    loginController = window.App.__container__.lookup('controller:login');
    loginController.setProperties({'loginError': true, 'isLoggingIn': false});
  });
```

I hope this clarifies the questions a bit better.

Cheers
Dave

Maybe I should close this here and open this question at Stackoverflow?

**Comment by heartsentwined** [comment]
It _still_ depends on where you're putting this callback. Simply put, it is ember best practice to access the controller where you are provided methods to, i.e. from the routes and controllers. For instance, that callback could have been defined in, say, the `App.SignInRoute`, and you would use `this.controllerFor()` to access it. However, you would have to go through the container if you define it, say, on the global namespace. But then, this latter case is not ember best practice.

**Comment by heartsentwined** [comment]
Personally I would do something like:

``` javascript
// let's say the template is specific to the sign in page
App.SignInRoute = Ember.Route.extend({
  events: {
    signIn: function() {
      // pre-sign in stuff, validations maybe
      App.Auth.on('signInError', function() { doSomething(); });
      // now do sign in stuff, calling App.signIn() etc
    }
  }
});
```

**Comment by kiwiupover** [comment]
Ok I get it now.

I really like the new time out feature a great inclusion.

Cheers

**Comment by heartsentwined** [comment]
Glad to help :smile:
