### ISSUE TITLE
Epf support

### ISSUE THREAD

**Issue by Globegitter** [heartsentwined/ember-auth#81]
There is this relatively new framework EPF (http://epf.io/, https://github.com/GroupTalent/epf) and I am thinking of switching because there are just a few major things that are quite painful with EmberData but ember-auth support would be necessary.
Do you think that would be a feature/module that could be added? Would be really helpful

**Comment by heartsentwined** [comment]
I am an early adopter of EPF myself. But I'm still working my way through the code base. An EPF module would have to ensure that it does capture all requests, taking into consideration how users would be calling its API. PRs welcome though - if you are faster than me. :smile:

**Comment by raphaelsaunier** [comment]
@heartsentwined, I'm considering writing an `epf` module for your library. Before I do this however, I was wondering if you had already looked into this. Is it as simple as patching the ajax method inside [rest_adapter.js](https://github.com/GroupTalent/epf/blob/master/lib/rest/rest_adapter.js#L548-L565) and translating methods calls (e.g. `store.find()` -> `session.load()`) or are there any other pitfalls you've identified?

**Comment by heartsentwined** [comment]
@raphaelsaunier You're most welcome to do so. I certainly looks like overriding the ajax would be fine, but I haven't gone through the whole code base to be sure of that.

**Comment by heartsentwined** [comment]
`epf` module introduced (not enabled by default). Also of note is that the auto-load current user feature now works with `epf` - in that the `epf` library returns a promise on `model.find()` calls, but `ember-data` returns the model directly. Both will now work.

**Comment by heartsentwined** [comment]
But not with `ember 1.0.0.rc8` yet - GroupTalent/epf#83
