### ISSUE TITLE
After urlAuthenticatable authentication, I am redirected

### ISSUE THREAD

**Issue by kevinansfield** [heartsentwined/ember-auth#87]
I'm using `urlAuthenticatable` so that a user can be logged in and redirected to the next signup step after confirming their account.

This used to work fine, now the authentication works but I am immediately redirected by the `actionRedirectable` away from the page that was requested.

My auth config is as follows:

```
App.Auth = Ember.Auth.create

  tokenKey: 'auth_token'
  tokenIdKey: 'user_id'
  userModel: 'App.User'

  signInEndPoint: '/users/sign_in'
  signOutEndPoint: '/users/sign_out'

  modules: [
    'emberData',
    'urlAuthenticatable',
    'authRedirectable',
    'actionRedirectable',
    'rememberable',
  ]

  rememberable:
    tokenKey: 'remember_token'
    period: 14 # days
    autoRecall: true

  urlAuthenticatable:
    paramsKey: 'auth'

  authRedirectable:
    route: 'home.sign_in'

  actionRedirectable:
    signOutRoute: 'home'
    signInRoute: 'newsfeed'
    signInSmart: true
    signInBlacklist: [
      'home',
      'home.sign_in',
      'home.confirmation_required',
      'sign_out'
    ]
```

When I access this url: `/signup/step_2?auth[auth_token]=xxx&auth[remember]=1`
I am authenticated but immediately redirected to the `newsfeed` route.

**Comment by kevinansfield** [comment]
ember-auth-source: 7.1.0
ember-source: 1.0.0.rc6.4
ember-data-source: 0.13

**Comment by heartsentwined** [comment]
Sounds like a duplicate of #69 - try the fix as we discussed in [this comment](https://github.com/heartsentwined/ember-auth/issues/69#issuecomment-20432137). (Move `actionRedirectable` to before `urlAuthenticatable`.)

Let me know if the issue persists.

**Comment by kevinansfield** [comment]
The advice in that comment seems backwards for this issue?

Previously I had the `rememberable` module too high so my `actionRedirectable` wasn't working. Now I have the `urlAuthenticatable` first which is what I want to authenticate before any others but I am still be redirected when I shouldn't be.

**Comment by kevinansfield** [comment]
Changing the order works but the ordering seems very counter-intuitive, should the redirect modules always come before the sign-in modules?

To me that seems strange as I would expect to be signed-in if possible before any redirection happens.

**Comment by heartsentwined** [comment]
I mean something like

``` coffee
App.Auth = Ember.Auth.create
  modules: [
    'emberData',
    'authRedirectable',
    'actionRedirectable',
    'urlAuthenticatable',
    'rememberable'
  ]
```

**Comment by heartsentwined** [comment]
This is bugging me too, we're having like 4-5 reports on this same ordering issue. I can't think of a good way of bringing the "register redirect" part of `actionRedirectable` forward though, I'll keep you updated when I have a solution.

**Comment by kevinansfield** [comment]
Cool, thanks for all your work on the library and your quick ticket response! I'll close the issue as the re-ordering seems to be working.
