### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < 

### ISSUE THREAD

**Issue by stimg** [heartsentwined/ember-auth#88]
ember-auth v 6.x

ember-auth.js line 268 (Auth.canonicalize method)

If auth response not a valid JSON (f.e. HTML error page) ember-auth fails with error. Maybe try-catch has sense on JSON.parse()?

UPDATE: it looks like in the version 7.x it is fixed.

Thanks for your great job!

**Comment by heartsentwined** [comment]
Yes, it is indeed reported and fixed in #74.
