### ISSUE TITLE
redirect to login fails on ember1.0.0-rc.7

### ISSUE THREAD

**Issue by remkoboschker** [heartsentwined/ember-auth#89]
The bug has been reported in the ember issues https://github.com/emberjs/ember.js/issues/3089

**Comment by heartsentwined** [comment]
Is this an ember-level bug then? From the issue referenced, it seems that this behavior is observed regardless of whether `ember-auth` is included or not.

**Comment by remkoboschker** [comment]
It probably is not. Thought you'd might like to now something's up.

**Comment by heartsentwined** [comment]
I'm monitoring the status of emberjs/ember.js#3089 in any case, thanks for the issue report

**Comment by heartsentwined** [comment]
Closing. This appears to be an `ember`-level bug.

**Comment by heartsentwined** [comment]
Please reopen if the issue persists even after emberjs/ember.js#3089 has been fixed.
