### ISSUE TITLE
UrlAuthenticatable can't override signInEndPoint of Ember.Auth

### ISSUE THREAD

**Issue by stimg** [heartsentwined/ember-auth#90]
UrlAuthenticatable uses signInEndPoint of Ember.Auth, but my server exposes two different end points for url and authentication with credentials. It would be good if I could (re)define signInEndPoint for url authentication in the urlAuthenticatable config.

**Comment by heartsentwined** [comment]
An unusual use case - nevertheless mark as enhancement, I'll code it when I have free time.

**Comment by heartsentwined** [comment]
Implemented.

For your use case, first you can set the `endPoint` option for the `urlAuthenticatable` module, and it will work as you expected:

``` coffeescript
App.Auth = Ember.Auth.create
  # ...
  modules: ['urlAuthenticatable']
  # remember to include any other modules you use

  urlAuthenticatable:
    paramsKey: 'auth'
    endPoint: '/url-authenticatable' # default null
```

This setup will send `urlAuthenticatable`-originated sign in requests to `/url-authenticatable`.

Next, you can also call `signIn` in userland code with the url overridden:

``` coffeescript
App.Auth.signIn  '/foo',
  data:
    'email': '(email value)'
    'password': '(password value)'
```

This sends a sign in request to `/foo`, regardless of what you have set in `signInEndPoint`. (omitting the first argument, i.e. the existing method call of passing an object as first argument, will still work).

More details at the [docs](http://ember-auth.herokuapp.com/docs).

**Comment by stimg** [comment]
Thank you for your efforts! Unfortunately it doesn't work for me. Something goes wrong by url creation. In the ajax request in `Auth.Request.send`, line 252 I see following Ajax.settings object: 

``` javascript
{
0: "c"
1: "r"
2: "o"
3: "s"
4: "s"
5: "-"
6: "a"
7: "u"
8: "t"
9: "h"
10: "o"
11: "r"
12: "i"
13: "z"
14: "e"
camelize: function () {
capitalize: function () {
classify: function () {
dasherize: function () {
dataType: "json"
decamelize: function () {
fmt: function () {
htmlSafe: function () {
loc: function () {
type: "POST"
underscore: function () {
url: "http://bimplus-dev.mantro.net/v2/authorize"
w: function () {
arguments: null
caller: null
length: 0
name: ""
prototype: Object
__proto__: function Empty() {}
<function scope>
__proto__: Object
}
```

My endpoint is splitted into single letters and url === signInEndPoint. So request is sent to the wrong url.

**Comment by heartsentwined** [comment]
Whoa! What happened?! I'm definitely digging into this

**Comment by stimg** [comment]
Also auth request is sent twice. It won't work in my case since cross token valid one time only. With second request valid auth data will be invalidated.

**Comment by bseng** [comment]
It does not work for me https://github.com/heartsentwined/ember-auth/issues/93 as well, after I put in the url it send a login request to the backend api without any of the parameters (email, password, remember, etc)

**Comment by heartsentwined** [comment]
I noticed a old function signature that hasn't included the custom end point as an argument. Presumably that is what is causing the bizarre behavior?

The fix has been merged at `9.x`. The usual code-generating [docs](http://ember-auth.herokuapp.com/) and [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide) to help with the transition.

Please try the upgrade and let me know if the issue persists.

**Comment by bseng** [comment]
I've upgraded to `9.0.6` and try the end point option `test-end-point` with sign-in. After sign-in the end point actually transit to `http://localhost:5000/test-end-point` and fail. I guess the correct one should be `http://localhost:5000/#/test-end-point`

**Comment by heartsentwined** [comment]
@bseng are you using the `hash` location or the `history` location, or a custom one? (`hash` is default)

**Comment by bseng** [comment]
I haven't set any location (don't know how to )so I believe is `hash`

**Comment by heartsentwined** [comment]
By the way, the end point is for _sending_ requests to the server. If you put, e.g.

``` coffeescript
App.Auth = Em.Auth.extend 
  # ...
  signInEndPoint: '/normal-end-point'
  urlAuthenticatable:
    endPoint: '/test-end-point'
```

That should only have the effect of sending sign-in requests from url authentication to '/test-end-point' instead of '/normal-end-point'.

**Comment by heartsentwined** [comment]
I'm skeptical that you would expect a (server api) end point like `/#/test-end-point`. Are you actually looking for the `actionRedirectable` module? That one handles post- sign in (and sign out) redirects to different routes in your ember app.

**Comment by bseng** [comment]
I'm actually refering to the `actionRedirectable` module and using the signIn options for one time redirect. Sorry for the confusion.

**Comment by heartsentwined** [comment]
There is no built-in one-time redirect config option in `actionRedirectable`, but I would do 

``` coffeescript
@auth.signIn().then => @transitionTo 'somewhere'
```

**Comment by bseng** [comment]
that works well, thanks
