### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by bkCDL** [heartsentwined/ember-auth#96]
I like your app. I am interesting in using it in my node.js app. As all the docs refer to Ruby, I am wondering... Does Ember-auth work only with Ruby on Rails or is it possible to use with Node?

Bryan

**Comment by heartsentwined** [comment]
`ember-auth` is framework-agnostic, although I do code in rails myself, so I used that as an example. Pick up the npm package at [`ember-auth`](https://npmjs.org/package/ember-auth) :smile:
