### ISSUE TITLE
Ember Data 1.0 Beta 1 breaks Ember-Auth

### ISSUE THREAD

**Issue by Globegitter** [heartsentwined/ember-auth#98]
You probably know that, but Ember Data 1.0 Beta 1 breaks ember-auth completely.

I can also provide some error messages if that helps. Though also, just because you added the rc8 break-warning, I don't seem to have any issues running ember-auth with Emberjs 1.0.0 final and Ember Data pre-Beta (http://builds.emberjs.com.s3.amazonaws.com/daily/20130827/ember-data.min.js)

As always, massive thanks for the work you are putting in here.

**Comment by heartsentwined** [comment]
`ember-data` - sorry, I saw only `0.0.5` and `0.13` in ruby source gems, so the library was only tested against those.

`ember rc8` - well at least it breaks the test suite. Unfortunately the [changes](http://emberjs.com/blog/2013/08/29/ember-1-0-rc8.html) affected us, and I haven't got enough free time around to figure those out yet.

I guess we're not the only project who felt the BC breaks in `rc8` though? I've already filed two issues at the `epf` project - GroupTalent/epf#83 and GroupTalent/epf#84 due to the `rc8` upgrade already...

**Comment by matthewrudy** [comment]
I'm interested to help out with this too.

`ember-auth` works fine with Ember 1.0.0
(at least for how I use it)

But `ember-data` 1.0.0.beta.1 is totally different.

The first thing I know is broken is;

It used to be `User.find(1)`, now it is `@store.find 'user', 1`

Currently

```
findUser: ->
    if @userId && (modelKey = @auth.userModel) && (model = Ember.get modelKey)
      if (@user = model.find @userId)?.then?
        model.find(@userId).then (m) => @user = m
```

I don't know why it calls find twice, but I'd hope it can just be;

```
findUser: ->
  if @userId && (modelKey = @auth.userModel)
    @store.find(modelKey, @userId)
```

That should return a promise with the latest ember-data

I don't know how to inject the `@store` from the app container

**Comment by heartsentwined** [comment]
We'd either have to move this to the `emberData` module, or let userland code specify their own find methods (with `ember-data`'s find being the default). There are at least three ways of calling find on a model now, depending on which adapter you use:
- `store.find()` - `ember-data`
- `Model.find()` - `ember-model`
- `session.load()` - `epf`

**Comment by somebody32** [comment]
Hi! I've also noticed some problems according Ember Auth and Data b1,
At first I've thought that it is an Ember Data bug and described it [here](http://discuss.emberjs.com/t/ember-data-1-0-save-problem/2433), but after some digging I've found that this is caused by injecting ember auth with ember-data module, so it looks like adding token to every request is breaking up something

**Comment by matthewrudy** [comment]
I'm going to give it a go tomorrow starting from scratch to build something similar to Ember Auth.
Will see how it goes.

**Comment by somebody32** [comment]
I've found the easy solution for the my problem above:

``` coffee
App.ApplicationAdapter = DS.RESTAdapter.extend
  ajax: (url, type, hash) ->
    if App.Auth.get("signedIn")
      hash = hash || {}
      hash.data = hash.data || {}
      hash.data[App.Auth.get('tokenKey')] = App.Auth.get('authToken')
    @_super(url, type, hash)
```

also, @heartsentwined maybe it will be better to base ORM modules not on your internal `Auth.send`, but on ORM's internal ajax call? And also rewrite `Auth.send` so it will use the currently activated ORM module, but not the own solution. I think this will help avoid problems like this in the future.

**Comment by Globegitter** [comment]
@somebody32 so did you basically fix ember-auth, or did you just add that in your app? Because I tried a similar fix for mine, but I still didn't get it to work fully (granted, I didn't spent much time on it so far and it might have had some other issues).

**Comment by somebody32** [comment]
@Globegitter I've added this just to my app and removed `ember-data` from modules list for `ember-auth`. Also my app doesn't depend on auto load for current user, so this fixes only my problem described [here](http://discuss.emberjs.com/t/ember-data-1-0-save-problem/2433)

**Comment by asia653** [comment]
Related issue: https://github.com/heartsentwined/ember-auth/issues/102

**Comment by heartsentwined** [comment]
`9.x` (latest version) now supports auto-loading current users for `ember-data` (also `epf` and `ember-model`). The usual code-generating [docs](http://ember-auth.herokuapp.com/) and [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide) to help with the transition.

Please reopen this ticket if it doesn't work.

**Comment by Globegitter** [comment]
@heartsentwined wow, thanks for all the great works. That looks amazing, will check it out soon.
