### ISSUE TITLE
Error callback not executing

### ISSUE THREAD

**Issue by miguelcobain** [heartsentwined/ember-auth#99]
Well, I want to execute some logic when a login fails.
Naturally, I return a `401` error code from my api when the credentials are wrong. However, the callback I register in Ember Auth doesn't fire.

This is probably related to jQuery, because the `fail` callback never executes. I've tried version 1.10 and 2.0.2 versions of jQuery.

I've also tried to return codes `400` and `500`, but with no success.

Any ideas? 

Thanks.

**Comment by miguelcobain** [comment]
Nevermind. The problem was that my api was returning some HTML (default behavior), and ember-auth failed to parse the string. Shouldn't this scenario fire the error callback as well?

**Comment by heartsentwined** [comment]
Debatable: is this a failed `JSON.parse` error (thus should `throw` an error directly), or should `ember-auth` "swallow" it as well, and just send it through the error hook? IMO the first would make more sense. Malformed server responses usually suggest fixing the server, or customizing the adapter. I'd say the error hook shouldn't catch these; instead it should contain semantically meaningful error statuses for app logic. A `422` response with details of model errors, for instance, would be meaningful; but a malformed server response? How can you expect to handle this error meaningfully in the client `ember` app?

**Comment by heartsentwined** [comment]
@miguelcobain This behavior has been standardized in `9.x`. It will (or, at least, _should_) now always reject as error.

``` coffeescript
# let's say server returns malformed response
auth.signIn().fail ->
  # handle the error here
```

The usual code-generating [docs](http://ember-auth.herokuapp.com/) and [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide) to help with the transition.

Please reopen the ticket if the actual behavior is different.
